import {REFUGE} from '../src/refuge-layout.js';
import {MERCHANTS} from '../src/merchants.js';
// Dev-only integration checks against the actual Phaser scene; restores the save.
import {state,save,openPanel,closePanel,finishRaid} from '../src/main.js';
import {newProfile,item,grid,put,flowField,equippedSkills} from '../src/core.js';
const report=document.createElement('pre');report.id='smoke-results';report.style.cssText='position:fixed;inset:15px;z-index:1000;background:#102018;color:white;padding:24px;overflow:auto';document.body.append(report);
const results=[];const assert=(ok,m)=>{if(!ok)throw Error(m);};
const test=(name,fn)=>{try{fn();results.push('PASS '+name);}catch(e){results.push('FAIL '+name+': '+e.message);console.error(e);}report.textContent=results.join('\n');};
while(!state.scene?.hero||!state.scene?.ui)await new Promise(r=>setTimeout(r,100));
const s=state.scene,original=structuredClone(state.profile);s.game.loop.sleep();
try{
 state.profile=newProfile();state.mode='hub';s.startHub();
 test('Five merchants have separate restocking catalogs and reachable interaction points',()=>{
  for(const o of s.objects.filter(o=>o.type==='vendor')){assert(o.merchantId in MERCHANTS,'unknown merchant');assert(s.canWalk(o.x,o.y+40,10),'blocked merchant '+o.merchantId);closePanel();s.hero.setPosition(o.x,o.y+40);s.interact(o);assert(s.activeVendor===o,'wrong active merchant');assert(s.vendorStock.items.every(i=>MERCHANTS[o.merchantId].stock.includes(i.type)),'mixed stock');const old=s.vendorStock.items[0];s.quickTransfer(old,'vendor');assert(s.vendorStock.items.some(i=>i.type===old.type&&i.id!==old.id),'not restocked');s.update(1,16);assert(state.panel==='vendor','closed near selected merchant');closePanel();}
  assert(s.objects.filter(o=>o.type==='vendor').length===5,'missing merchants');s.activeVendor=null;
 });
 test('Refuge chapel walls are solid, buildings stay opaque, and services have connected approaches',()=>{
  closePanel();s.startHub();for(const [x,y,w,h]of REFUGE.chapel.walls){for(let xx=x+12;xx<x+w-10;xx+=20)for(let yy=y+10;yy<y+h-5;yy+=20)assert(!s.canWalk(xx,yy,4),'hole in chapel wall');}
  const step=16,seen=new Set(),queue=[REFUGE.hero.map(n=>Math.round(n/step))];seen.add(queue[0].join(','));for(let n=0;n<queue.length;n++){const [x,y]=queue[n];for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,k=nx+','+ny;if(!seen.has(k)&&s.canWalk(nx*step,ny*step,10)){seen.add(k);queue.push([nx,ny]);}}}
  for(const o of s.objects)assert(queue.some(([x,y])=>Math.hypot(x*step-o.x,y*step-o.y)<70),'disconnected '+o.title);
  for(const [x,y]of [[1536,1500],[1580,1360],[1536,1590]]){s.hero.setPosition(x,y);s.update(200,16);assert(s.refugeArchitecture.every(o=>o.alpha===1),'architecture faded');}s.hero.setPosition(...REFUGE.hero);
 });
 test('Alt movement keys reach Phaser and suppress browser defaults',()=>{for(const code of ['KeyW','KeyA','KeyS','KeyD']){const event=new KeyboardEvent('keydown',{code,key:code.slice(3).toLowerCase(),keyCode:code.charCodeAt(3),altKey:true,bubbles:true,cancelable:true});window.dispatchEvent(event);assert(event.defaultPrevented,'browser accelerator not captured');assert(s.input.keyboard.manager.queue.includes(event),'Phaser lost movement event');window.dispatchEvent(new KeyboardEvent('keyup',{code,keyCode:code.charCodeAt(3),bubbles:true,cancelable:true}));}s.input.keyboard.manager.queue.length=0;s.input.keyboard.resetKeys();});
 test('Map selection reserves a bag item and consumes it only on launch',()=>{closePanel();const map=item('hauntedmap');put(state.profile.bag,map);openPanel('expedition');s.held={it:map,g:state.profile.bag,source:'bag'};s.insertRaidMap();assert(state.profile.bag.items.some(i=>i.id===map.id),'map consumed on insertion');closePanel();assert(state.profile.bag.items.some(i=>i.id===map.id),'map lost on cancel');openPanel('expedition');s.launchSelectedMap();assert(state.mode==='raid'&&s.raidModifiers.health===1.3&&s.raidModifiers.loot===.35,'map modifiers not applied');assert(!state.profile.bag.items.some(i=>i.id===map.id),'map duplicated');s.returnToHub();});
 test('Discard confirmation is transactional and raid drops retain gem identity',()=>{state.profile=newProfile();state.mode='hub';s.startHub();const it=state.profile.bag.items[0];openPanel('inventory');s.held={it,g:state.profile.bag,source:'bag'};s.dropHeldItem();assert(state.panel==='destroy'&&state.profile.bag.items.includes(it),'deleted before confirmation');s.confirmDiscard(false);assert(state.profile.bag.items.includes(it),'cancel deleted item');s.held={it,g:state.profile.bag,source:'bag'};s.dropHeldItem();s.confirmDiscard(true);assert(!state.profile.bag.items.includes(it),'confirmation did not delete');closePanel();state.mode='raid';s.startRaid();const gem=item('healing');put(state.profile.bag,gem);openPanel('inventory');s.held={it:gem,g:state.profile.bag,source:'bag'};s.dropHeldItem();const drop=s.objects.find(o=>o.item?.id===gem.id);assert(drop&&drop.sprite.texture.key==='original-moon-0','ground gem uses skill icon');assert(!state.profile.bag.items.some(i=>i.id===gem.id),'drop duplicated');assert(!s.objects.some(o=>o.title?.includes('Останки')),'remains still generated');s.returnToHub();});
 test('Level choices interrupt inventory and damage produces feedback without a global contact cooldown',()=>{state.mode='raid';s.startRaid();s.invincible=0;const hp=s.hp;s.takeHeroDamage(1);s.takeHeroDamage(2);assert(s.hp===hp-3&&s.hurtFlash>0&&s.invincible===0,'contact damage suppressed');s.enemies=[];s.enemyBullets=[];s.xp=s.level*10;openPanel('inventory');s.update(1000,16);assert(state.panel==='level','inventory blocked level choices');s.returnToHub();});
 state.profile=newProfile();state.mode='hub';s.startHub();
 test('All UI children use screen coordinates',()=>{openPanel('vendor');assert(s.canvasPanel.list.every(o=>o.scrollFactorX===0&&o.scrollFactorY===0),'camera-dependent hitbox');});
 test('Panels remain aligned after canvas resize',()=>{const host=document.getElementById('game'),css=host.style.cssText;try{host.style.width='2000px';host.style.height='920px';s.scale.setParentSize(2000,920);s.resize();openPanel('vendor');const bag=s.gridTargets.find(t=>t.source==='bag'),vendor=s.gridTargets.find(t=>t.source==='vendor');assert(Math.abs(s.uiWidth*s.uiScale-2000)<1,'viewport width');assert(bag.x+bag.g.w*bag.cell<=s.uiWidth,'bag clipped');assert(vendor.x+vendor.g.w*vendor.cell<bag.x,'panels overlap');assert(s.canvasPanel.list.every(o=>o.scrollFactorX===0&&o.scrollFactorY===0),'resized hitbox');}finally{host.style.cssText=css;s.scale.setParentSize(host.clientWidth,host.clientHeight);s.resize();openPanel('vendor');}});
 test('Vendor purchase and sale through grid actions',()=>{const it=s.vendorStock.items.find(i=>i.type==='nova'),gold=state.profile.gold;s.held={it,source:'vendor',g:s.vendorStock};s.placeHeld({g:state.profile.bag,source:'bag'});assert(state.profile.gold===gold,'free purchase charged gold');assert(state.profile.bag.items.some(i=>i.id===it.id),'purchase inventory');s.held={it,source:'bag',g:state.profile.bag};s.sellHeld();assert(state.profile.gold===gold+it.value,'sale credit');assert(!state.profile.bag.items.some(i=>i.id===it.id),'sale removes item');});
 test('Native drag preview keeps full item footprint and rejects occupied cells',()=>{
  const it=state.profile.bag.items.find(i=>i.type==='sword');openPanel('inventory');const t=s.gridTargets.find(t=>t.source==='bag');
  s.beginItemDrag({it,source:'bag',g:t.g,grabX:0,grabY:1},{x:(t.x+(it.x+.5)*32)*s.uiScale,y:(t.y+(it.y+1.5)*32)*s.uiScale});
  assert(s.heldIcon.list.length>1&&s.dragPreview.active,'drag art and sockets');assert(s.canvasPanel.list.filter(o=>o.itemId===it.id).every(o=>!o.visible),'source duplicate is visible');
  const x=it.x,y=it.y;s.placeHeld(t,0,0);assert(it.x===x&&it.y===y&&s.held,'invalid move consumed item');closePanel();assert(t.g.items.includes(it),'cancel lost item');
 });
 test('Socket extraction and insertion use the cursor without changing gem ownership on cancel',()=>{
  closePanel();openPanel('inventory');const gear=state.profile.equipment.weapon,gem=gear.sockets[0];const pointer={x:100,y:100,rightButtonDown:()=>true};
  s.handleSocket(gear,0,pointer);assert(s.held?.source==='socket'&&s.held.it===gem,'gem not on cursor');closePanel();assert(gear.sockets[0]===gem,'cancel lost gem');
  openPanel('inventory');s.handleSocket(gear,0,pointer);s.placeHeld({g:state.profile.bag,source:'bag'});assert(!gear.sockets[0]&&state.profile.bag.items.some(i=>i.id===gem.id),'gem was not extracted');
  const bagGem=state.profile.bag.items.find(i=>i.id===gem.id);s.beginItemDrag({it:bagGem,source:'bag',g:state.profile.bag},pointer);s.handleSocket(gear,0,pointer);assert(gear.sockets[0]?.id===gem.id&&!state.profile.bag.items.some(i=>i.id===gem.id),'gem insertion');closePanel();
 });
 test('Socket masks reveal full icons only on Alt or when carrying a gem',()=>{openPanel('inventory');s.keys.ALT.isDown=false;s.updateSocketVisibility();assert(s.socketViews.length>0,'missing sockets');assert(s.socketViews.every(v=>!v.full.visible&&v.mask.visible),'full sockets obscure item');s.keys.ALT.isDown=true;s.updateSocketVisibility();assert(s.socketViews.every(v=>v.full.visible&&!v.mask.visible),'Alt did not expand sockets');s.keys.ALT.isDown=false;s.updateSocketVisibility();closePanel();});
 test('Native item size and socket geometry match equipment, bag and cursor',()=>{
  openPanel('inventory');const gear=state.profile.equipment.weapon,texture=s.itemTexture(gear),equipped=s.canvasPanel.list.find(o=>o.texture?.key===texture);assert(equipped,'missing equipped item');const scale=equipped.scaleX;
  s.beginItemDrag({it:gear,source:'equipment',slot:'weapon'},{x:100,y:100});assert(s.heldIcon.list.find(o=>o.texture?.key===texture).scaleX===scale,'item rescaled on cursor');closePanel();
 });
 test('Action picker exposes only equipped skills and commits a slot selection',()=>{
  closePanel();state.profile.equipment.boots.sockets=[item('blink')];s.openActionPicker(1);assert(s.actionPicker?.active,'no picker');const button=s.actionPicker.list.find(o=>o.input&&o.skillChoice);assert(button,'no skill choice');button.emit('pointerdown',{},0,0,{stopPropagation(){}});assert(state.profile.activeSlots[1],'skill not assigned');
 });
 test('Vendor allows free purchases at zero gold',()=>{openPanel('vendor');const it=s.vendorStock.items[0];state.profile.gold=0;s.held={it,source:'vendor',g:s.vendorStock};s.placeHeld({g:state.profile.bag,source:'bag'});assert(s.vendorStock.items.some(i=>i.type===it.type&&i.id!==it.id),'stock not replenished');assert(state.profile.bag.items.some(i=>i.id===it.id),'free purchase failed');assert(state.profile.gold===0,'free purchase changed gold');});
 test('Solid scenery blocks movement and trees still reveal the hero',()=>{closePanel();const b=s.solidProps[0];assert(!s.canWalk(b.x+b.w/2,b.y+b.h/2),'solid is passable');const tree=s.occluders.find(o=>o.texture?.key==='original-tree-a-0'),bounds=tree.getBounds();let point=null;for(let y=30;y<tree.height-50&&!point;y+=8)for(let x=8;x<tree.width-8;x+=8)if(s.textures.getPixelAlpha(x,y,tree.texture.key)>128){point={x:bounds.left+x,y:bounds.top+y+30};break;}assert(point,'tree silhouette missing');const old={x:s.hero.x,y:s.hero.y};s.hero.setPosition(point.x,point.y);s.update(10,16);assert(tree.alpha<1,'tree occlusion transparency');s.hero.setPosition(old.x,old.y);});
 test('Left click interacts with the world while inventory is open; E is a skill key',()=>{closePanel();const o=s.objects.find(o=>o.type==='expedition');s.hero.setPosition(o.x,o.y+58);openPanel('inventory');o.sprite.emit('pointerdown',{leftButtonDown:()=>true},0,0,{stopPropagation(){}});assert(state.panel==='expedition','click blocked by inventory');closePanel();s.input.keyboard.emit('keydown',{code:'KeyE',repeat:false});assert(!s.interactionRequested&&s.activeRequested===2,'E still interacts');s.activeRequested=false;});
 test('Raid creates searchable rooms and fog',()=>{closePanel();state.mode='raid';s.startRaid();assert(s.objects.filter(o=>o.type==='container').length>=60,'containers');assert(s.objects.filter(o=>o.type==='container').every(o=>o.sprite?.active&&o.x===o.sprite.x&&o.y===o.sprite.y),'container art/hitbox alignment');const first=s.map.rooms[0],field=flowField(s.navigationMap,first.cx,first.cy);assert(s.map.rooms.every(r=>Number.isFinite(field[r.cy][r.cx])),'furniture blocks room connectivity');assert(s.objects.filter(o=>o.type==='pickup').length>=18,'loose loot');assert(s.visibleTiles.size>0&&s.explored.size<s.map.w*s.map.h/2,'fog');for(let i=0;i<120;i++)s.update(i*20,20);});
 test('Enemy rifts delay combat and shared skill descriptions expose effective values',()=>{s.spawnEnemy();const e=s.enemies.at(-1);assert(e.spawning>0&&e.spawnPortal?.active&&e.sprite.alpha===0,'no rift emergence');const hp=e.hp;s.hitEnemy(e,100,0xffffff);assert(e.hp===hp,'forming enemy takes damage');for(let n=0;n<20;n++)s.updateEnemies(.05);assert(e.spawning===0&&e.sprite.alpha===1,'spawn did not complete');const skill=equippedSkills(state.profile.equipment)[0];s.showSkillTooltip(skill,500,500);const texts=s.tooltip.list.filter(o=>typeof o.text==='string').map(o=>o.text).join(' ');assert(texts.includes('Перезарядка')&&!texts.includes('золота'),'noncombat tooltip');s.tooltip.destroy();s.tooltip=null;});
 test('Every exit and searchable container has a reachable interaction position',()=>{const first=s.map.rooms[0],field=flowField(s.navigationMap,first.cx,first.cy);for(const o of s.objects.filter(o=>['container','exit','rune'].includes(o.type))){let reachable=false;for(let y=Math.floor(o.y/32)-3;y<=Math.floor(o.y/32)+3;y++)for(let x=Math.floor(o.x/32)-3;x<=Math.floor(o.x/32)+3;x++)if(Number.isFinite(field[y]?.[x])&&Math.hypot(x*32+16-o.x,y*32+16-o.y)<76&&s.canWalk(x*32+16,y*32+16))reachable=true;assert(reachable,'unreachable '+o.title);}assert(s.objects.some(o=>o.grid?.items.some(it=>it.type==='key')),'missing extraction key');});
 test('Equipment does not change the fixed character',()=>{const equipment=state.profile.equipment;s.attackUntil=0;s.animateHero(0,false);const key=s.hero.anims.currentAnim.key;try{state.profile.equipment={};s.updateHeroAppearance();s.animateHero(0,false);assert(s.hero.anims.currentAnim.key===key,'equipment changed character');assert(!s.heroWeapon?.active&&!s.heroHelmet?.active&&!s.heroShield?.active,'detached gear layers');for(const motion of ['idle','walk','attack'])for(const direction of ['down','left','up'])assert(s.anims.get(`hero-${motion}-${direction}`).frames.length>=4,'incomplete animation');}finally{state.profile.equipment=equipment;}});
 test('Automatic skills cannot occupy active slots',()=>{
  const skill=state.profile.equipment.weapon.sockets.find(g=>g?.kind==='skill');state.profile.activeSlots=[skill.id,null,null];s.renderOverlay(true);assert(state.profile.activeSlots.every(id=>id!==skill.id),'passive skill remained assigned');
 });
 test('Archer aims at hero and rotates the arrow',()=>{const x=s.hero.x+40,y=s.hero.y;const sprite=s.add.sprite(x,y,'original-mob-archer-walk-left-0');s.enemies=[{sprite,type:'archer',hp:30,maxHP:30,speed:30,hit:0,shoot:0}];s.updateEnemies(.016);const arrow=s.enemyBullets.at(-1);assert(arrow&&arrow.vx<0&&Math.abs(arrow.vy)<.01,'arrow aim');assert(Math.abs(Math.abs(arrow.sprite.rotation)-Math.PI)<.01,'arrow rotation');});
 test('Containers hide undiscovered items and preserve reveal boundary',()=>{const o=s.objects.find(o=>o.type==='container');s.hero.setPosition(o.x,o.y+42);s.fogStamp=-1;s.updateFog();s.interact(o);assert(state.panel==='container','open container');assert(o.revealed===0,'loot pre-revealed');for(let i=0;i<22;i++)s.update(100+i*50,50);assert(o.revealed===1,'progressive identification');assert(s.searchFill,'missing identification bar');closePanel();});
 test('Extraction and death preserve stash',()=>{put(state.profile.stash,item('relic'));const id=state.profile.stash.items[0].id;state.mode='raid';finishRaid(true);assert(state.mode==='result'&&state.profile.equipment.weapon,'extraction');state.mode='raid';finishRaid(false);assert(!state.profile.equipment.weapon&&!state.profile.bag.items.length,'death loss');assert(state.profile.stash.items[0].id===id,'stash lost');});
 test('Result return clears drag state and restores inventory input',()=>{s.returnToHub();assert(state.mode==='hub'&&!state.panel,'return mode');assert(!s.held&&!s.heldIcon,'stale drag');s.input.keyboard.emit('keydown',{code:'KeyI'});assert(state.panel==='inventory'&&s.canvasPanel.active,'inventory input after death');closePanel();state.mode='raid';finishRaid(false);s.input.keyboard.emit('keydown',{code:'Escape'});assert(state.mode==='hub'&&!state.panel,'keyboard return after repeated death');});
 test('Repeated deaths clear held items and keep every hub object clickable',()=>{for(let n=0;n<3;n++){state.profile=newProfile();state.mode='raid';s.startRaid();openPanel('inventory');const it=state.profile.bag.items[0];s.beginItemDrag({it,g:state.profile.bag,source:'bag'},{x:100,y:100,downTime:44});finishRaid(false);s.returnToHub();assert(!s.held&&!s.canvasPanel&&!state.search&&!state.panel,'stale interface state');for(const o of s.objects.filter(o=>['vendor','stash','expedition'].includes(o.type))){s.hero.setPosition(o.x,o.y+40);o.sprite.emit('pointerdown',{leftButtonDown:()=>true},0,0,{stopPropagation(){}});assert(state.panel===o.type,'blocked '+o.type);closePanel();}}});
 test('Click with an already held item outside inventory opens discard immediately',()=>{state.profile=newProfile();s.returnToHub();openPanel('inventory');const it=state.profile.bag.items[0];s.beginItemDrag({it,g:state.profile.bag,source:'bag'},{x:100,y:100,downTime:3});s.input.emit('pointerdown',{x:s.scale.width/2,y:300,leftButtonDown:()=>true});assert(state.panel==='destroy','click did not open discard');s.confirmDiscard(false);assert(state.profile.bag.items.some(i=>i.id===it.id),'cancel lost item');closePanel();});
 test('Tab toggles the map and Escape closes it',()=>{s.input.keyboard.emit('keydown-TAB',{preventDefault(){}});assert(s.mapExpanded,'map did not open');s.input.keyboard.emit('keydown',{code:'Escape'});assert(!s.mapExpanded&&!state.panel,'map close opened pause');});


 test('Movement remains live in vendor and stash',()=>{for(const panel of ['vendor','stash']){openPanel(panel);const x=s.hero.x;s.keys.D.isDown=true;s.update(2000,50);s.keys.D.isDown=false;assert(s.hero.x!==x,'movement blocked in '+panel);closePanel();}});
 test('Expansion skills, duration, active healing and blink work',()=>{
  state.profile=newProfile();state.mode='raid';s.startRaid();s.invincible=99999;
  for(const [type,weapon]of [['meteor','staff'],['rain','bow'],['juggernaut','sword']]){
   const gear=item(weapon),gem=item(type);gear.sockets=[gem,item('duration')];state.profile.equipment.weapon=gear;const skill=equippedSkills(state.profile.equipment).find(g=>g.id===gem.id);assert(skill,'unavailable '+type);const before=s.areaEffects.length;s.castExpansionSkill(skill,{x:s.hero.x+40,y:s.hero.y},{});assert(s.areaEffects.length===before+1,'no effect '+type);if(type!=='meteor')assert(s.areaEffects.at(-1).life>gem.duration,'duration support ignored');
  }
  const ring=item('ring'),heal=item('healing');ring.sockets=[heal];const boots=item('boots'),blink=item('blink');boots.sockets=[blink];state.profile.equipment.ring=ring;state.profile.equipment.boots=boots;
  s.hp=40;state.profile.activeSlots=[null,null,null];s.updateCombat(.016);assert(s.hp===40,'healing auto-cast');state.profile.activeSlots=[heal.id,blink.id,null];s.activeRequested=1;s.updateCombat(.016);assert(s.hp===75,'healing failed');s.activeRequested=1;s.updateCombat(.016);assert(s.hp===75,'healing cooldown bypass');
  const x=s.hero.x,y=s.hero.y;const skill=equippedSkills(state.profile.equipment).find(g=>g.id===blink.id);s.castExpansionSkill(skill,{x:x+70,y},{});assert(s.canWalk(s.hero.x,s.hero.y,10),'blink entered solid');assert(Math.hypot(s.hero.x-x,s.hero.y-y)>0,'blink did not move');
  for(let i=0;i<100;i++)s.updateCombat(.05);assert(!s.areaEffects.length,'expired effects retained');
 });
 test('Bosses spawn once at 3, 6 and 9 minutes and reset after death',()=>{
  s.enemies.forEach(e=>{e.sprite.destroy();e.healthBar?.destroy();});s.enemies=[];s.bossStages.clear();s.elapsed=179;s.updateEnemies(.016);assert(!s.enemies.some(e=>e.boss),'early boss');
  for(const time of [180,360,540]){s.elapsed=time;for(let n=0;n<5;n++)s.updateEnemies(.016);assert(s.bossStages.size===time/180,'boss schedule '+time);}
  assert(s.enemies.filter(e=>e.boss).length===3,'duplicate boss');for(let n=0;n<400;n++)s.updateEnemies(.05);assert(s.areaEffects.some(f=>f.hostile)||s.enemyBullets.length>0,'boss has no abilities');s.renderOverlay(true);assert(s.bossHUD?.active,'boss health display');finishRaid(false);s.returnToHub();assert(!s.bossStages.size&&!s.areaEffects.length,'boss state leaked into refuge');
 });

 test('Left click on an empty socket picks up the whole item',()=>{
  state.profile=newProfile();const gear=state.profile.bag.items.find(it=>it.type==='sword');openPanel('inventory');const target=s.gridTargets.find(t=>t.source==='bag'),point=s.socketTargets.find(t=>t.it.id===gear.id);s.keys.ALT.isDown=true;s.updateSocketVisibility();const ring=s.socketViews.flatMap(v=>v.full.list).find(o=>o.texture?.key==='original-socket-ring-0'&&o.itemId===gear.id&&Math.abs(o.x+10-point.x)<1&&Math.abs(o.y+10-point.y)<1);
  ring.emit('pointerdown',{x:point.x*s.uiScale,y:point.y*s.uiScale,downTime:99999,event:{},rightButtonDown:()=>false},0,0,{stopPropagation(){}});assert(s.held?.it.id===gear.id,'empty socket consumed item click');closePanel();
 });
 test('Ctrl right click loots a revealed item and right click equips from chest',()=>{
  const chest={title:'Test chest',x:s.hero.x,y:s.hero.y,grid:grid(4,4),revealed:2,progress:0};put(chest.grid,item('sword'));put(chest.grid,item('healing'));const weapon=chest.grid.items[0],gem=chest.grid.items[1];openPanel('container',chest);
  const event={stopPropagation(){}};s.canvasPanel.list.find(o=>o.itemHitId===weapon.id).emit('pointerdown',{event:{},rightButtonDown:()=>true},0,0,event);assert(state.profile.equipment.weapon.id===weapon.id,'direct equip failed');
  s.canvasPanel.list.find(o=>o.itemHitId===gem.id).emit('pointerdown',{event:{ctrlKey:true},rightButtonDown:()=>true},0,0,event);assert(state.profile.bag.items.some(it=>it.id===gem.id),'ctrl right click failed');closePanel();
 });
 test('Meteor multishot and boss animations use full native frames',()=>{
  state.mode='raid';s.startRaid();s.invincible=99999;const gem=item('meteor'),skill={...gem,supports:['multi']};const before=s.areaEffects.length;s.castExpansionSkill(skill,{x:s.hero.x+80,y:s.hero.y},{multi:2,haste:0,duration:0});assert(s.areaEffects.length-before===3,'multishot meteor count');
  s.elapsed=540;for(let i=0;i<8;i++)s.updateEnemies(.016);const bosses=s.enemies.filter(e=>e.boss);assert(bosses.length===3,'boss fixtures');s.renderOverlay(true);s.renderOverlay(true);assert(s.bossRows.filter(r=>r.row.visible).length===3,'missing parallel boss bars');assert(s.bossHUD.list.length===3,'duplicated boss rows');
  for(const e of bosses){const old=e.sprite.anims.currentFrame.index;e.sprite.preUpdate(1000,180);assert(e.sprite.anims.currentFrame.index!==old,'boss animation frozen');s.hitEnemy(e,1,0xffaa00);s.updateEnemies(.2);assert(e.sprite.tintTopLeft===0xffffff&&!e.sprite.tintFill,'boss tint stuck');}
  const gurag=bosses.find(e=>e.type==='gurag');gurag.cast=0;gurag.phase=0;s.updateEnemies(.016);const slam=s.areaEffects.find(f=>f.hostile&&f.bossType==='gurag');assert(slam?.marker?.active,'missing animated windup');const hp=s.hp;s.updateCombat(.4);assert(s.hp===hp,'damage before impact');s.updateCombat(.7);assert(!s.areaEffects.includes(slam),'telegraph was not cleaned up');assert(s.children.list.some(o=>o.texture?.key==='original-ground-crack-0'),'missing stone impact');
   assert(bosses.every(e=>!e.nameLabel),'boss overhead name remains');s.releaseBossAttack(gurag,{phase:2,x:s.hero.x,y:s.hero.y});const rocks=s.areaEffects.filter(f=>f.type==='boulder');assert(rocks.length===8,'radial stones missing');const startY=rocks[0].art.y;s.updateCombat(.2);assert(rocks[0].art.y!==startY,'stone flight is static');s.bossDeath(gurag);assert(gurag.pendingAttack===null&&s.tweens.getTweensOf(gurag.sprite).length>0,'boss death has no transition');
   const reaper=bosses.find(e=>e.type==='reaper');reaper.cast=0;reaper.phase=2;s.updateEnemies(.016);assert(reaper.pendingAttack?.left>0,'missing windup');for(let n=0;n<23;n++)s.updateEnemies(.05);assert(s.enemyBullets.some(b=>b.sprite.anims?.currentAnim?.key==='boss-scythe'),'scythes not animated');
  const chest=s.objects.find(o=>o.type==='container');s.hero.setPosition(chest.x,chest.y+30);s.fogStamp=-1;s.updateFog();s.keys.ALT.isDown=true;s.update(4000,16);assert(chest.label.visible,'alt did not reveal container');s.keys.ALT.isDown=false;s.update(4016,16);finishRaid(false);s.returnToHub();
 });
}finally{state.profile=original;state.mode='hub';state.panel=null;s.startHub();save();s.game.loop.wake();report.textContent=results.join('\n')+'\n\n'+results.filter(r=>r.startsWith('PASS')).length+'/'+results.length+' passed. Original profile restored.';}
