// Dev-only integration checks against the actual Phaser scene; restores the save.
import {state,save,openPanel,closePanel,finishRaid} from '../src/main.js';
import {newProfile,item,grid,put,flowField} from '../src/core.js';
const report=document.createElement('pre');report.id='smoke-results';report.style.cssText='position:fixed;inset:15px;z-index:1000;background:#102018;color:white;padding:24px;overflow:auto';document.body.append(report);
const results=[];const assert=(ok,m)=>{if(!ok)throw Error(m);};
const test=(name,fn)=>{try{fn();results.push('PASS '+name);}catch(e){results.push('FAIL '+name+': '+e.message);console.error(e);}report.textContent=results.join('\n');};
while(!state.scene?.hero||!state.scene?.ui)await new Promise(r=>setTimeout(r,100));
const s=state.scene,original=structuredClone(state.profile);s.game.loop.sleep();
try{
 state.profile=newProfile();state.mode='hub';s.startHub();
 test('All UI children use screen coordinates',()=>{openPanel('vendor');assert(s.canvasPanel.list.every(o=>o.scrollFactorX===0&&o.scrollFactorY===0),'camera-dependent hitbox');});
 test('Vendor purchase and sale through grid actions',()=>{const it=s.vendorStock.items.find(i=>i.type==='nova'),gold=state.profile.gold;s.held={it,source:'vendor',g:s.vendorStock};s.placeHeld({g:state.profile.bag,source:'bag'});assert(state.profile.gold===gold-it.value*2,'purchase charge');assert(state.profile.bag.items.some(i=>i.id===it.id),'purchase inventory');s.held={it,source:'bag',g:state.profile.bag};s.sellHeld();assert(state.profile.gold===gold-it.value,'sale credit');assert(!state.profile.bag.items.some(i=>i.id===it.id),'sale removes item');});
 test('Insufficient funds leave purchase unchanged',()=>{const it=s.vendorStock.items[0];state.profile.gold=0;s.held={it,source:'vendor',g:s.vendorStock};s.placeHeld({g:state.profile.bag,source:'bag'});assert(s.vendorStock.items.includes(it),'stock lost');assert(!state.profile.bag.items.includes(it),'free purchase');});
 test('Furniture blocks movement and becomes transparent behind hero',()=>{closePanel();const b=s.solidProps[0];assert(!s.canWalk(b.x+b.w/2,b.y+b.h/2),'solid is passable');const x=s.hero.x,y=s.hero.y;s.hero.setPosition(b.sprite.x,b.sprite.y-140);s.update(10,16);assert(b.sprite.alpha<1,'occlusion transparency');s.hero.setPosition(x,y);});
 test('Hover and E open portal without mouse movement',()=>{const o=s.objects.find(o=>o.type==='expedition');s.hero.setPosition(o.x,o.y+58);o.sprite.emit('pointerover');s.keys.E._justDown=true;s.update(20,16);assert(state.panel==='expedition','E did not open expedition');assert(!s.pendingInteraction,'unexpected click movement');});
 test('Raid creates searchable rooms and fog',()=>{closePanel();state.mode='raid';s.startRaid();assert(s.objects.filter(o=>o.type==='container').length>=60,'containers');const first=s.map.rooms[0],field=flowField(s.navigationMap,first.cx,first.cy);assert(s.map.rooms.every(r=>Number.isFinite(field[r.cy][r.cx])),'furniture blocks room connectivity');assert(s.objects.filter(o=>o.type==='pickup').length>=40,'loose loot');assert(s.visibleTiles.size>0&&s.explored.size<s.map.w*s.map.h/2,'fog');for(let i=0;i<120;i++)s.update(i*20,20);});
 test('Archer aims at hero and rotates the arrow',()=>{const x=s.hero.x+180,y=s.hero.y;const sprite=s.add.sprite(x,y,'original-mob-archer-walk-left-0');s.enemies=[{sprite,type:'archer',hp:30,maxHP:30,speed:30,hit:0,shoot:0}];s.updateEnemies(.016);const arrow=s.enemyBullets.at(-1);assert(arrow&&arrow.vx<0&&Math.abs(arrow.vy)<.01,'arrow aim');assert(Math.abs(Math.abs(arrow.sprite.rotation)-Math.PI)<.01,'arrow rotation');});
 test('Containers hide undiscovered items and preserve reveal boundary',()=>{const o=s.objects.find(o=>o.type==='container');s.hero.setPosition(o.x,o.y+42);s.fogStamp=-1;s.updateFog();s.interact(o);assert(state.panel==='container','open container');assert(o.revealed===0,'loot pre-revealed');for(let i=0;i<22;i++)s.update(100+i*50,50);assert(o.revealed===1,'progressive identification');assert(s.searchFill,'missing identification bar');closePanel();});
 test('Extraction and death preserve stash',()=>{put(state.profile.stash,item('relic'));const id=state.profile.stash.items[0].id;state.mode='raid';finishRaid(true);assert(state.mode==='result'&&state.profile.equipment.weapon,'extraction');state.mode='raid';finishRaid(false);assert(!state.profile.equipment.weapon&&!state.profile.bag.items.length,'death loss');assert(state.profile.stash.items[0].id===id,'stash lost');});
}finally{state.profile=original;state.mode='hub';state.panel=null;s.startHub();save();s.game.loop.wake();report.textContent=results.join('\n')+'\n\n'+results.filter(r=>r.startsWith('PASS')).length+'/'+results.length+' passed. Original profile restored.';}
