import Phaser from 'phaser';
import assets from './original-assets.json';
import { state, save, toast, openPanel, closePanel } from './main.js';
import { grid, put, item, rollLoot, rng, flowField, RARITIES, DEFS, equippedSkills, starter } from './core.js';
import { equip, unequip, socketGem, unsocket, transfer } from './inventory.js';

const textStyle = {fontFamily:'Georgia, serif',fontSize:'14px',color:'#d9c895',stroke:'#090709',strokeThickness:0,resolution:2};
const color = it => Phaser.Display.Color.HexStringToColor(RARITIES[it?.rarity || 0].color).color;
const slots = {weapon:[78,142,92,124],shield:[302,142,92,124],armor:[207,159,60,92],helmet:[207,64,60,76],gloves:[110,312,60,60],boots:[302,312,60,60],belt:[207,278,60,36],ring:[172,263,32,32],ring2:[270,263,32,32],amulet:[278,108,32,42]};
const original = (scene,key,n=0) => `original-${key}-${n}`;
export function preloadOriginal(scene) {
  for(const [key,frames] of Object.entries(assets)) for(let n=0;n<frames.length;n++) scene.load.image(original(scene,key,n),`${import.meta.env.BASE_URL}assets/original/${frames[n].file}`);
}
function img(s,parent,x,y,key,w,h){const i=s.add.image(x,y,key).setOrigin(0); if(w) i.setDisplaySize(w,h);if(parent){parent.add(i);i.setScrollFactor(0);i.cameraFilter=s.cameras.main.id;}return i;}
function label(s,parent,x,y,value,size=14,col='#d9c895'){const t=s.add.text(x,y,value,{...textStyle,fontSize:`${size}px`,color:col});t.texture.setFilter(Phaser.Textures.FilterMode.LINEAR);if(parent){parent.add(t);t.setScrollFactor(0);t.cameraFilter=s.cameras.main.id;}return t;}
function icon(s,parent,x,y,it,maxW,maxH){const t=s.textures.get(s.itemTexture(it)).getSourceImage();const i=img(s,parent,x,y,s.itemTexture(it)).setOrigin(.5).setScale(Math.min(maxW/t.width,maxH/t.height));i.cameraFilter=s.cameras.main.id;return i;}
function button(s,parent,x,y,w,title,action){const b=img(s,parent,x,y,'original-button-0',w,30).setInteractive({useHandCursor:true});label(s,parent,x+w/2,y+15,title,12).setOrigin(.5);b.on('pointerover',()=>b.setTint(0xffd5b0)).on('pointerout',()=>b.clearTint()).on('pointerdown',(_p,_x,_y,e)=>{e.stopPropagation();action();});return b;}
function frame(s,parent,x,y,w,h){const f=s.add.nineslice(x,y,'original-stash-0','plain',w,h,8,8,36,4).setOrigin(0);parent.add(f);f.setScrollFactor(0);f.cameraFilter=s.cameras.main.id;return f;}
function socketPositions(n,w,h){const cols=w<45?1:2,rows=Math.ceil(n/cols),gap=28;return Array.from({length:n},(_,i)=>{const row=Math.floor(i/cols),col=cols===1?0:row%2?1-i%2:i%2;return [w/2+(col-(cols-1)/2)*gap,h/2+(row-(rows-1)/2)*gap];});}
function lineOfSight(map,x0,y0,x1,y1){let dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1,e=dx+dy;for(let n=0;n<30;n++){if(x0===x1&&y0===y1)return true;if(!map.tiles[y0]?.[x0])return false;const e2=2*e;if(e2>=dy){e+=dy;x0+=sx;}if(e2<=dx){e+=dx;y0+=sy;}}return false;}

export function installPresentation(Scene) {
 const baseCreate=Scene.prototype.create, baseReset=Scene.prototype.resetWorld, baseUpdate=Scene.prototype.update, baseRaid=Scene.prototype.startRaid, baseInteract=Scene.prototype.interact,baseObject=Scene.prototype.addObject,basePortal=Scene.prototype.portal;
 Object.assign(Scene.prototype,{
  addObject(type,x,y,texture,title){if(type==='expedition')y=292;const o=baseObject.call(this,type,x,y,texture,title);if(texture?.startsWith('original-')&&o.sprite)o.sprite.setScale(['original-books-0','original-rack-0','original-bench-0','original-cage-0'].includes(texture)?.5:1);return o;},
  portal(x,y,color){if(state.mode==='hub')y=290;basePortal.call(this,x,y,color);this.add.rectangle(x,y-15,90,115,0xffffff,.001).setDepth(y+10).setInteractive({useHandCursor:true}).on('pointerdown',()=>{const o=this.objects.find(o=>Math.hypot(o.x-x,o.y-y)<50&&(o.type==='expedition'||o.type==='exit'));if(o)this.interact(o);});},
  create(){for(const [key,frames]of Object.entries(assets))if(key.startsWith('atk-')||key.startsWith('death-')||key==='fireball'||key==='slash')this.anims.create({key:`original-${key}`,frames:frames.map((f,n)=>({key:`original-${key}-${n}`})),frameRate:14,repeat:key==='fireball'||key==='slash'?-1:0});const tex=this.textures.get('original-inventory-3');tex.add('no-charms',0,40,0,388,720);tex.add('edge',0,526,0,8,720);this.textures.get('original-stash-0').add('plain',0,0,0,560,112);baseCreate.call(this);this.input.mouse.disableContextMenu();this.input.setTopOnly(true);this.input.on('pointermove',p=>{if(this.heldIcon)this.heldIcon.setPosition(p.x/this.uiScale,p.y/this.uiScale);});this.input.on('pointerdown',(p,over)=>{if(state.panel||over.length||!p.leftButtonDown())return;const pos=this.cameras.main.getWorldPoint(p.x/this.uiScale,p.y/this.uiScale);if(this.map.tiles[Math.floor(pos.y/32)]?.[Math.floor(pos.x/32)]){this.pendingInteraction={type:'walk',x:pos.x,y:pos.y};this.interactionPath=flowField(this.map,Math.floor(pos.x/32),Math.floor(pos.y/32));}});this.input.on('pointerup',p=>{if(!this.held||Math.hypot(p.x/this.uiScale-p.downX/this.uiScale,p.y/this.uiScale-p.downY/this.uiScale)<6)return;const t=this.gridTargets.find(t=>p.x/this.uiScale>=t.x&&p.y/this.uiScale>=t.y&&p.x/this.uiScale<t.x+t.g.w*t.cell&&p.y/this.uiScale<t.y+t.g.h*t.cell);if(t)this.placeHeld(t,Math.floor((p.x/this.uiScale-t.x)/t.cell),Math.floor((p.y/this.uiScale-t.y)/t.cell));else if(this.panelKind==='vendor'&&p.x/this.uiScale>=0&&p.x/this.uiScale<396)this.sellHeld();else for(const [slot,[x,y,w,h]]of Object.entries(slots)){if(p.x/this.uiScale>=this.panelX+x&&p.x/this.uiScale<this.panelX+x+w&&p.y/this.uiScale>=y&&p.y/this.uiScale<y+h){const gear=state.profile.equipment[slot];if(['skill','support'].includes(this.held.it.kind)&&gear){const i=socketPositions(gear.sockets.length,w,h).findIndex(([sx,sy])=>Math.hypot(p.x/this.uiScale-this.panelX-x-sx,p.y/this.uiScale-y-sy)<16);if(i>=0)this.inventoryAction(()=>socketGem(state.profile,gear,i,this.held.it.id));}else if(((this.held.it.slot||this.held.it.kind)===slot||this.held.it.type==='ring'&&slot==='ring2'))this.inventoryAction(()=>equip(state.profile,this.held.it.id,slot));break;}}});},
  resetWorld(){this.ui=null;this.canvasPanel=null;this.canvasDetail=null;this.tooltip=null;this.held=null;this.heldIcon=null;this.fog=null;this.explored=new Set();this.visibleTiles=new Set();this.fogStamp=-1;this.solidProps=[];this.pendingInteraction=null;baseReset.call(this);},
  itemTexture(it){const gems={fire:'ruby',arrow:'emerald',slash:'topaz',nova:'sapphire',multi:'moon',haste:'emerald',pierce:'topaz'};if(gems[it.type])return `original-${gems[it.type]}-0`;if(['staff','bow','armor'].includes(it.type))return `original-${it.type}-0`;if(it.type==='sword')return 'original-weapon-0';if(assets['item-'+it.type])return `original-item-${it.type}-0`;return it.icon==='coin'?'hs-coin-0':`${it.icon}-0`;},
  createCanvasHud(){this.ui=this.add.container(0,0).setDepth(10000).setScrollFactor(0);this.uiTexts={};this.uiMode=null;this.renderOverlay(true);},
  renderOverlay(force=false){if(!this.ui?.active)return;const w=this.uiWidth,h=this.uiHeight,p=state.profile;if(!force&&this.uiMode===state.mode&&state.mode==='hub'){this.drawMinimap();return;}
   if(force||this.uiMode!==state.mode){this.ui.removeAll(true);this.uiMode=state.mode;this.uiTexts={};
    img(this,this.ui,10,0,'original-health-12',256,128);label(this,this.ui,90,12,'Изгнанник',17,'#e73559');
    this.ui.add(this.add.image(10,18,'original-knight-idle-down-0','portrait').setOrigin(0).setDisplaySize(40,36));
    this.hpFill=this.add.rectangle(48,50,180,12,0xb4212d).setOrigin(0);this.manaFill=this.add.rectangle(48,70,180,10,0x304cbd).setOrigin(0);this.ui.add([this.hpFill,this.manaFill]);
    this.uiTexts.hp=label(this,this.ui,138,51,'',10,'#ffffff').setOrigin(.5,0);label(this,this.ui,138,70,'100 / 100',9,'#d5dfff').setOrigin(.5,0);
    this.uiTexts.timer=label(this,this.ui,w-235,17,'',15);this.uiTexts.wave=label(this,this.ui,w-235,39,'',11);
    this.hudMap=this.add.graphics();this.ui.add(this.hudMap);
    img(this,this.ui,0,h-123,'original-hud-12');this.uiTexts.gold=label(this,this.ui,61,h-51,'',14);this.uiTexts.level=label(this,this.ui,44,h-23,'',11);
    const abilities=equippedSkills(p.equipment);abilities.slice(0,5).forEach((it,i)=>{img(this,this.ui,116+i*40,h-67,'hs-skill-frame-0',38,38);icon(this,this.ui,135+i*40,h-48,it,28,28);});
    button(this,this.ui,335,h-49,79,'I  Сумка',()=>{if(state.mode!=='result'&&state.panel!=='level')state.panel?closePanel():openPanel('inventory');});
    this.uiTexts.hint=label(this,this.ui,w/2,h-30,'',13).setOrigin(.5);
    
    this.updateHeroAppearance();this.markUI(this.ui);
   }
   const hp=Math.max(0,this.hp??100);this.hpFill?.setDisplaySize(Math.max(.01,180*hp/(this.maxHP||100)),12);this.uiTexts.hp?.setText(`${Math.ceil(hp)} / ${this.maxHP||100}`);this.uiTexts.gold?.setText(`${p.gold}`);this.uiTexts.level?.setText(`Уровень ${this.level||1}`);
   const left=Math.max(0,210-(this.elapsed||0));this.uiTexts.timer?.setText(state.mode==='raid'?`До тьмы  ${Math.floor(left/60)}:${String(Math.floor(left%60)).padStart(2,'0')}`:'Последний огонь');this.uiTexts.wave?.setText(state.mode==='raid'?`Волна ${this.wave}   •   Убито ${this.kills}`:'Убежище странников');this.drawMinimap();
  },
  drawMinimap(){if(!this.hudMap)return;if(state.mode==='hub'){this.hudMap.clear();return;}const ox=this.uiWidth-235,oy=64,sx=210/this.map.w,sy=135/this.map.h;this.hudMap.clear();for(let y=0;y<this.map.h;y++)for(let x=0;x<this.map.w;x++)if(this.map.tiles[y][x]&&(state.mode!=='raid'||this.explored.has(y*this.map.w+x)))this.hudMap.fillStyle(0x958778,.65).fillRect(ox+x*sx,oy+y*sy,sx,sy);if(this.hero)this.hudMap.fillStyle(0x46e5e5).fillCircle(ox+this.hero.x/32*sx,oy+this.hero.y/32*sy,2);},
  setInteractionText(t){this.uiTexts?.hint?.setText(t);},
  toastCanvas(message){if(!this.ui?.active)return;this.toastObject?.destroy();this.toastObject=label(this,this.ui,this.uiWidth/2,90,message,14).setOrigin(.5);const t=this.toastObject;this.time.delayedCall(3500,()=>t.active&&t.destroy());},
  closeCanvasPanel(){this.tooltip?.destroy();this.tooltip=null;this.heldIcon?.destroy();this.heldIcon=null;this.held=null;this.searchFill=null;this.searchItemFill=null;this.canvasPanel?.destroy();this.canvasPanel=null;},
  openCanvasPanel(panel,search=state.search){this.pendingInteraction=null;this.closeCanvasPanel();this.panelKind=panel;this.lastItemClick=null;this.canvasPanel=this.add.container(0,0).setScrollFactor(0).setDepth(11000);const parent=this.canvasPanel;
   this.panelX=this.uiWidth-436;this.panelY=0;this.gridTargets=[];
   const inventory=['inventory','stash','container','vendor'].includes(panel);
   if(inventory){parent.add(this.add.image(this.panelX+40,0,'original-inventory-3','no-charms').setOrigin(0));parent.add(this.add.image(this.panelX+428,0,'original-inventory-3','edge').setOrigin(0));const blocker=this.add.zone(this.panelX+40,0,396,720).setOrigin(0).setInteractive();parent.addAt(blocker,0);label(this,parent,this.panelX+238,12,'ИНВЕНТАРЬ',18).setOrigin(.5,0);
    this.drawCanvasEquipment(this.panelX,0);this.drawCanvasGrid(state.profile.bag,this.panelX+46,425,'bag',Infinity,32);
    label(this,parent,this.panelX+66,686,`${state.profile.gold} золота`,14);
    if(panel!=='inventory')this.drawSidePanel(panel,search);
   }else{this.panelX=Math.floor((this.uiWidth-460)/2)-40;const mh=panel==='pause'?230:570;this.modalTop=Math.floor((this.uiHeight-mh)/2);frame(this,parent,this.panelX+40,this.modalTop,460,mh);const blocker=this.add.zone(0,0,this.uiWidth,this.uiHeight).setOrigin(0).setInteractive();parent.addAt(blocker,0);label(this,parent,this.panelX+270,this.modalTop+22,{expedition:'ЭКСПЕДИЦИЯ',pause:'ПАУЗА',help:'ПАМЯТКА',result:'ИТОГ ВЫЛАЗКИ'}[panel]||panel,20).setOrigin(.5,0);if(panel==='expedition')this.drawCanvasExpedition();else if(panel==='result')this.drawCanvasResult();else this.drawCanvasHelp();}
   const close=img(this,parent,this.panelX+48,inventory?8:this.modalTop+12,'hs-button-close-0',22,22).setInteractive();close.on('pointerdown',()=>{if(panel==='result')return;closePanel();});this.markUI(parent);
  },
  drawCanvasGrid(g,x,y,source,revealed=Infinity,cell=32){const parent=this.canvasPanel;const target={g,x,y,cell,source};this.gridTargets.push(target);
   for(let yy=0;yy<g.h;yy++)for(let xx=0;xx<g.w;xx++){const tile=img(this,parent,x+xx*cell,y+yy*cell,'original-cell-0',cell,cell).setInteractive();tile.on('pointerdown',(p,_x,_y,e)=>{e.stopPropagation();if(this.held)this.placeHeld(target,xx,yy);});}
   g.items.forEach((it,index)=>{const px=x+it.x*cell,py=y+it.y*cell,hidden=index>=revealed;const zone=this.add.rectangle(px,py,it.w*cell,it.h*cell,0xffffff,.001).setOrigin(0).setInteractive({useHandCursor:true});parent.add(zone);
    if(hidden){label(this,parent,px+it.w*cell/2,py+it.h*cell/2,index===revealed?'⋯':'?',20,'#776952').setOrigin(.5);if(index===revealed){img(this,parent,px+3,py+it.h*cell-10,'original-identify-0',it.w*cell-6,6);this.searchItemFill=this.add.rectangle(px+5,py+it.h*cell-8,it.w*cell-10,2,0xc6ab69).setOrigin(0);parent.add(this.searchItemFill);}return;}
    icon(this,parent,px+it.w*cell/2,py+it.h*cell/2,it,it.w*cell-6,it.h*cell-6);const pip=this.add.graphics().lineStyle(1,color(it),.65).strokeRect(px+1,py+1,it.w*cell-2,it.h*cell-2);parent.add(pip);
    zone.on('pointerover',p=>this.showItemTooltip(it,p.x/this.uiScale,p.y/this.uiScale));zone.on('pointerout',()=>{this.tooltip?.destroy();this.tooltip=null;});zone.on('pointerdown',(p,_x,_y,e)=>{e.stopPropagation();if(this.held){this.placeHeld(target,it.x,it.y);return;}if(p.rightButtonDown()){if(source==='bag'&&it.kind==='armor'||source==='bag'&&it.kind==='weapon')this.inventoryAction(()=>equip(state.profile,it.id));else if(it.type==='nova'){toast('Установите камень в предмет и нажмите на него для назначения на Q');}return;}
     if(p.event.shiftKey||p.downTime-(this.lastItemClick?.time||0)<320&&this.lastItemClick?.id===it.id){this.quickTransfer(it,source);this.lastItemClick=null;return;}this.lastItemClick={id:it.id,time:p.downTime};this.held={it,source,g};this.heldIcon=icon(this,null,p.x/this.uiScale,p.y/this.uiScale,it,45,65).setDepth(14000).setScrollFactor(0);this.tooltip?.destroy();this.tooltip=null;
    });
   });return target;
  },
  inventoryAction(fn){if(!fn())return toast('Недостаточно места или несовместимый предмет');save();this.renderOverlay(true);this.openCanvasPanel(state.panel,state.search);},
  placeHeld(target,x,y){const h=this.held;if(!h)return;if(h.source==='equipment'){if(target.source!=='bag')return;this.inventoryAction(()=>{if(!put(target.g,h.it,x,y))return false;state.profile.equipment[h.slot]=null;return true;});}else if(h.source==='vendor'){if(target.source!=='bag')return;this.inventoryAction(()=>{const price=h.it.free?0:h.it.value*2;if(state.profile.gold<price||!transfer(h.g,target.g,h.it.id,null,x,y))return false;state.profile.gold-=price;return true;});}else if(target.source==='vendor')this.sellHeld();else this.inventoryAction(()=>transfer(h.g,target.g,h.it.id,state.search,x,y));},
  sellHeld(){if(this.held?.source!=='bag')return;const it=this.held.it;this.inventoryAction(()=>{state.profile.bag.items=state.profile.bag.items.filter(i=>i.id!==it.id);state.profile.gold+=it.free?0:it.value;put(this.vendorStock,it);return true;});},
  quickTransfer(it,source){if(source==='vendor'){this.held={it,source,g:this.vendorStock};return this.placeHeld({source:'bag',g:state.profile.bag});}let from=source==='bag'?state.profile.bag:source==='stash'?state.profile.stash:state.search?.grid;let to=source==='bag'?(state.panel==='stash'?state.profile.stash:state.panel==='container'?state.search?.grid:null):state.profile.bag;
   if(state.panel==='vendor'&&source==='bag'){state.profile.bag.items=state.profile.bag.items.filter(i=>i.id!==it.id);state.profile.gold+=it.free?0:it.value;save();this.renderOverlay(true);this.openCanvasPanel('vendor');return;}
   if(!to)return this.inventoryAction(()=>equip(state.profile,it.id));this.inventoryAction(()=>transfer(from,to,it.id,state.search));
  },
  drawCanvasEquipment(x,y){const parent=this.canvasPanel,p=state.profile;for(const [slot,[sx,sy,w,h]] of Object.entries(slots)){const it=p.equipment[slot],quality=['normal','normal','rare','satanic'][it?.rarity||0],backType=slot==='weapon'||slot==='shield'?'weapon':slot==='armor'?'armor':slot==='helmet'?'helmet':slot==='belt'?'belt':'jewelry';img(this,parent,x+sx,y+sy,`original-equip-${backType}-${quality}-0`,w,h);const z=this.add.rectangle(x+sx,y+sy,w,h,0xffffff,.001).setOrigin(0).setInteractive({useHandCursor:true});parent.add(z);
    if(it)icon(this,parent,x+sx+w/2,y+sy+h/2,it,w-12,h-12);else img(this,parent,x+sx+w*.2,y+sy+h*.2,`original-slot-${slot==='ring2'?'ring':slot}-0`,w*.6,h*.6).setAlpha(.32);
    z.on('pointerover',p=>{if(it)this.showItemTooltip(it,p.x/this.uiScale,p.y/this.uiScale);});z.on('pointerout',()=>{this.tooltip?.destroy();this.tooltip=null;});z.on('pointerdown',(pointer,_x,_y,e)=>{e.stopPropagation();if(this.held){const h=this.held;if(h.source==='bag'&&((h.it.slot||h.it.kind)===slot||h.it.type==='ring'&&slot==='ring2'))this.inventoryAction(()=>equip(p,h.it.id,slot));else toast('Этот предмет не подходит в выбранный слот');}else if(it&&pointer.rightButtonDown())this.inventoryAction(()=>unequip(p,slot));else if(it){this.held={it,source:'equipment',slot};this.heldIcon=icon(this,null,pointer.x/this.uiScale,pointer.y/this.uiScale,it,45,65).setDepth(14000).setScrollFactor(0);this.tooltip?.destroy();this.tooltip=null;}});
    const points=socketPositions(it?.sockets?.length||0,w,h);if(points.length>1){const links=this.add.graphics().lineStyle(4,0x4c3425).beginPath();points.forEach(([px,py],i)=>i?links.lineTo(x+sx+px,y+sy+py):links.moveTo(x+sx+px,y+sy+py));links.strokePath();links.lineStyle(2,0xb19764).beginPath();points.forEach(([px,py],i)=>i?links.lineTo(x+sx+px,y+sy+py):links.moveTo(x+sx+px,y+sy+py));links.strokePath();parent.add(links);}
    (it?.sockets||[]).forEach((gem,i)=>{const gx=x+sx+points[i][0],gy=y+sy+points[i][1];const socket=img(this,parent,gx-11,gy-11,'original-socket-ring-0',22,22).setInteractive({useHandCursor:true});if(gem)icon(this,parent,gx,gy,gem,18,20);socket.on('pointerover',p=>{if(gem)this.showItemTooltip(gem,p.x/this.uiScale,p.y/this.uiScale,it);});socket.on('pointerout',()=>{this.tooltip?.destroy();this.tooltip=null;});socket.on('pointerdown',(pointer,_x,_y,e)=>{e.stopPropagation();if(this.held)this.inventoryAction(()=>socketGem(p,it,i,this.held.it.id));else if(pointer.rightButtonDown())this.inventoryAction(()=>unsocket(p,it,i));else if(gem?.type==='nova'){p.active=p.active===gem.id?null:gem.id;save();this.renderOverlay(true);toast(p.active?'Ледяное кольцо назначено на Q':'Ледяное кольцо применяется автоматически');}});});
   }},
  showItemTooltip(it,px,py,gear){if(this.held)return;this.tooltip?.destroy();const width=300,height=it.sockets?245:185;const x=Math.max(8,Math.min(this.panelX-width+30,px-width-16)),y=Math.min(this.uiHeight-height-8,Math.max(12,py-40));this.tooltip=this.add.container(x,y).setScrollFactor(0).setDepth(13500);const bg=this.add.rectangle(0,0,width,height,0x050405,.97).setOrigin(0).setStrokeStyle(1,0x827443);this.tooltip.add(bg);label(this,this.tooltip,150,16,it.name,17,RARITIES[it.rarity].color).setOrigin(.5);label(this,this.tooltip,150,42,RARITIES[it.rarity].name,12).setOrigin(.5);const desc=it.damage?`Урон: ${Math.round(it.damage*RARITIES[it.rarity].mult)}\nТип оружия: ${it.weapon}`:it.armor?`Броня: +${Math.round(it.armor*RARITIES[it.rarity].mult)}`:it.description||'Добыча из подземелья';label(this,this.tooltip,18,72,desc,13,'#c4c4bf').setWordWrapWidth(264);if(it.sockets){label(this,this.tooltip,18,126,`Сокеты: ${it.sockets.filter(Boolean).length} / ${it.sockets.length}`,13);it.sockets.forEach((g,i)=>{img(this,this.tooltip,18+i*38,154,'original-socket-0',28,28);if(g)icon(this,this.tooltip,32+i*38,168,g,23,25);});label(this,this.tooltip,18,193,'Поддержки усиливают соседний камень.',11);}this.markUI(this.tooltip);label(this,this.tooltip,18,height-28,`${state.panel==='vendor'&&this.vendorStock?.items.includes(it)?'Покупка':'Продажа'}: ${it.free?0:state.panel==='vendor'&&this.vendorStock?.items.includes(it)?it.value*2:it.value} золота`,12,'#c6ad62');},
  drawSidePanel(panel,search){const x=0,parent=this.canvasPanel;frame(this,parent,x,0,396,720);const blocker=this.add.rectangle(x,0,396,720,0xffffff,.001).setOrigin(0).setInteractive();parent.addAt(blocker,0);blocker.on('pointerdown',()=>{if(panel==='vendor')this.sellHeld();});label(this,parent,198,14,panel==='stash'?'ТАЙНИК':panel==='vendor'?'ТОРГОВЕЦ':search?.title||'ОБЫСК',18).setOrigin(.5,0);
   if(panel==='stash')this.drawCanvasGrid(state.profile.stash,38,88,'stash');
   if(panel==='container'&&search){const gx=(396-search.grid.w*40)/2;this.drawCanvasGrid(search.grid,gx,110,'container',search.revealed,40);label(this,parent,198,78,search.revealed<search.grid.items.length?'ОБЫСК':'ОБЫСК ЗАВЕРШЁН',12).setOrigin(.5);this.searchFill=this.add.rectangle(gx,110+search.grid.h*40+14,search.grid.w*40,3,0xc6ab69).setOrigin(0);parent.add(this.searchFill);button(this,parent,98,620,200,'Забрать всё',()=>{for(const it of [...search.grid.items.slice(0,search.revealed)])transfer(search.grid,state.profile.bag,it.id,search);save();this.openCanvasPanel('container',search);});}
   if(panel==='vendor'){if(!this.vendorStock){this.vendorStock=grid(12,8);for(const type of ['staff','sword','bow','armor','helmet','gloves','boots','belt','ring','amulet','shield','fire','arrow','slash','nova','multi','haste','pierce'])put(this.vendorStock,item(type,1));}this.drawCanvasGrid(this.vendorStock,6,88,'vendor');label(this,parent,26,682,`${state.profile.gold} золота`,14);if(!Object.values(state.profile.equipment).some(i=>i?.kind==='weapon')&&![...state.profile.bag.items,...state.profile.stash.items].some(i=>i.kind==='weapon'))button(this,parent,48,620,300,'Бесплатный походный комплект',()=>{Object.assign(state.profile.equipment,starter());save();this.renderOverlay(true);this.openCanvasPanel('vendor');});}
  },
  refreshCanvasSearch(){if(state.panel==='container'&&!this.held)this.openCanvasPanel('container',state.search);},
  drawCanvasExpedition(){const x=this.panelX+70,y=this.modalTop,p=this.canvasPanel;label(this,p,x+200,y+75,'КАТАКОМБЫ КРЕПОСТИ',19).setOrigin(.5);img(this,p,x+165,y+120,'hs-portal-0',70,95);label(this,p,x,y+255,'Обыщите хранилища и найдите выход.\n\nКлюч • руны • 35 убийств\n\nЧерез 3:30 подземелье поглотит тьма.\nПри смерти снаряжение будет потеряно.',15).setLineSpacing(5);button(this,p,x+35,y+470,330,'Начать вылазку',()=>{state.mode='raid';state.profile.inRaid=true;state.profile.runs++;save();closePanel();this.startRaid();});},
  drawCanvasHelp(){const x=this.panelX+105,y=this.modalTop;button(this,this.canvasPanel,x,y+110,330,'Продолжить',()=>closePanel());},
  drawCanvasResult(){const x=this.panelX+80;label(this,this.canvasPanel,x,170,this.resultSuccess?'ЭВАКУАЦИЯ УСПЕШНА':'ВЫЛАЗКА ПОТЕРЯНА',23,this.resultSuccess?'#ded294':'#c35757');label(this,this.canvasPanel,x,260,this.resultSuccess?'Добыча сохранена.':'Снаряжение и рюкзак потеряны.\nТайник в убежище уцелел.',15);button(this,this.canvasPanel,x,420,340,'Вернуться в убежище',()=>{state.panel=null;state.mode='hub';this.startHub();});},
  openCanvasLevel(options,apply){this.levelChoices={options,apply};this.openCanvasPanel('level');this.canvasPanel.removeAll(true);const x=(this.uiWidth-494)/2;frame(this,this.canvasPanel,x-20,10,534,660);label(this,this.canvasPanel,x+247,40,'СИЛА ПРОБУЖДАЕТСЯ',22).setOrigin(.5);options.forEach((o,i)=>{button(this,this.canvasPanel,x+38,170+i*140,418,o.name,()=>{apply(o);state.panel=null;this.closeCanvasPanel();this.renderOverlay(true);});label(this,this.canvasPanel,x+48,211+i*140,o.text,13).setWordWrapWidth(390);});this.markUI(this.canvasPanel);},
  resize(){this.uiScale=Math.max(.75,this.scale.gameSize.height/720);this.uiWidth=this.scale.gameSize.width/this.uiScale;this.uiHeight=720;this.uiCamera?.setSize(this.scale.gameSize.width,this.scale.gameSize.height).setOrigin(0).setZoom(this.uiScale);this.vignette?.setDisplaySize(this.scale.gameSize.width,this.scale.gameSize.height);if(this.ui?.active)this.renderOverlay(true);if(state.panel==='level'&&this.levelChoices)this.openCanvasLevel(this.levelChoices.options,this.levelChoices.apply);else if(state.panel)this.openCanvasPanel(state.panel,state.search);},
  drawMap(hub){const random=rng(hub?72:this.seed);this.solidProps=[];const tex=this.textures.get(hub?'original-fall-0':'original-floor-0');if(!tex.has('tile-0'))for(let y=0;y<tex.source[0].height/32;y++)for(let x=0;x<14;x++)tex.add(`tile-${y*14+x}`,0,x*32,y*32,32,32);
   const wall=this.textures.get('original-wall-0');if(!wall.has('cap')){wall.add('cap',0,0,0,64,24);wall.add('face',0,0,24,48,72);}
   for(let y=0;y<this.map.h;y++)for(let x=0;x<this.map.w;x++){if(this.map.tiles[y][x]){this.add.image(x*32,y*32,tex.key,`tile-${(y%4)*14+2+x%12}`).setOrigin(0).setDepth(-50);}else if(this.map.tiles[y+1]?.[x]){this.add.image(x*32,y*32-30,'original-wall-0','face').setOrigin(0).setDisplaySize(32,62).setDepth(-10);this.add.image(x*32,y*32-42,'original-wall-0','cap').setOrigin(0).setDisplaySize(32,16).setDepth(-9);}else if(this.map.tiles[y]?.[x-1]||this.map.tiles[y]?.[x+1])this.add.image(x*32,y*32,'original-wall-0','cap').setOrigin(0).setDisplaySize(32,32).setDepth(-9);}
   if(hub){this.add.image(544,240,'hs-town-hall-0').setOrigin(.5,1).setDepth(240);for(const [x,y] of [[250,260],[830,260],[260,665],[835,665]])this.torch(x,y);for(const [x,y,key] of [[140,430,'hs-dead-tree-0'],[940,440,'hs-dead-tree2-0'],[180,660,'hs-dead-tree-0'],[910,730,'hs-dead-tree2-0'],[360,480,'hs-street-lamp-0'],[760,490,'hs-street-lamp-right-0'],[270,535,'hs-bush-0'],[800,610,'hs-rock-0']])this.placeWorldProp(x,y,key,1);for(let n=0;n<45;n++){const x=100+random()*890,y=250+random()*480;if(Math.abs(x-540)<150)continue;this.placeWorldProp(x,y,n%3?'hs-bush-0':'original-rubble-0',.4+random()*.3);}}
   else for(const [index,r] of this.map.rooms.entries()){this.torch((r.x+1)*32,(r.y+1)*32);this.torch((r.x+r.w-1)*32,(r.y+r.h-2)*32);const keys=['rack','books','cage','bench','table'];const key=keys[index%keys.length];this.placeWorldProp((r.x+r.w-3)*32,(r.y+3)*32,`original-${key}-0`,key==='table'?1:.5);for(let n=0;n<8;n++){const px=(r.x+1+random()*(r.w-2))*32,py=(r.y+1+random()*(r.h-2))*32;if(Math.abs(px-(r.cx*32+16))<70&&Math.abs(py-(r.cy*32+16))<70)continue;this.placeWorldProp(px,py,n%3===0?'original-rubble-0':n%3===1?'hs-chains-0':'original-body-0',n%3===0?.5:1);}}
  },
  startRaid(){baseRaid.call(this);const random=this.random;for(const [index,r]of this.map.rooms.entries()){for(let n=0;n<3;n++){const x=(r.x+2+n*2)*32+16,y=(r.y+r.h-2)*32;const kind=['barrel','chest','books','rack','body'][((index+n)%5)];const o=this.addObject('container',x,y,`original-${kind}-0`,{barrel:'Бочка с припасами',chest:'Деревянный сундук',books:'Книжный шкаф',rack:'Стойка с оружием',body:'Останки искателя'}[kind]);o.grid=grid(kind==='rack'?5:4,4);o.revealed=0;o.progress=0;for(let j=0;j<2+Math.floor(random()*3);j++)put(o.grid,rollLoot(random));}for(let n=0;n<3;n++){const it=rollLoot(random),x=(r.x+3+random()*(r.w-6))*32,y=(r.y+3+random()*(r.h-6))*32;const o=this.addObject('pickup',x,y,this.itemTexture(it),it.name);o.item=it;o.sprite.setScale(.65);}}
   this.updateFog();},
  interact(o){if(state.panel)return;if(Math.hypot(o.x-this.hero.x,o.y-this.hero.y)>76){this.pendingInteraction=o;this.interactionPath=flowField(this.map,Math.floor(o.x/32),Math.floor(o.y/32));return;}if(state.mode==='raid'&&!this.visibleTiles.has(Math.floor(o.y/32)*this.map.w+Math.floor(o.x/32)))return;if(o.type==='pickup'){if(!put(state.profile.bag,o.item))return toast('Рюкзак заполнен');o.sprite?.destroy();o.label?.destroy();this.objects=this.objects.filter(v=>v!==o);save();toast(`Подобрано: ${o.item.name}`);return;}baseInteract.call(this,o);},
  createFog(){this.explored=new Set();this.visibleTiles=new Set();this.fog=this.add.graphics().setDepth(6900);this.fogStamp=-1;this.updateFog();},
  updateFog(){if(!this.fog||state.mode!=='raid')return;const tx=Math.floor(this.hero.x/32),ty=Math.floor(this.hero.y/32),stamp=ty*this.map.w+tx;if(stamp===this.fogStamp)return;this.fogStamp=stamp;this.visibleTiles=new Set();for(let y=ty-8;y<=ty+8;y++)for(let x=tx-8;x<=tx+8;x++)if(x>=0&&y>=0&&x<this.map.w&&y<this.map.h&&Math.hypot(x-tx,y-ty)<8&&lineOfSight(this.map,tx,ty,x,y)){this.visibleTiles.add(y*this.map.w+x);this.explored.add(y*this.map.w+x);}
   this.fog.clear();for(let y=0;y<this.map.h;y++)for(let x=0;x<this.map.w;x++){const key=y*this.map.w+x;if(!this.visibleTiles.has(key))this.fog.fillStyle(0x070608,this.explored.has(key)?.78:1).fillRect(x*32,y*32,32,32);}
  },
  makeHero(x,y){this.hero=this.add.sprite(x,y,'hero-0').setVisible(false);this.shadow=this.add.ellipse(x,y+12,27,10,0x000000,.4);this.heroRing=this.add.ellipse(x,y+13,25,9).setStrokeStyle(1,0x978055,.25);this.heroLight=this.add.circle(x,y,1,0,0);this.heroModel=this.add.container(x,y).setDepth(y+20);this.heroParts={};this.heroDirection='down';const parts=['left_lower_leg','right_lower_leg','left_upper_leg','right_upper_leg','pelvis','torso','left_upper_arm','right_upper_arm','left_lower_arm','right_lower_arm','left_shoulder','right_shoulder','head'];for(const part of parts){const i=this.add.image(0,0,`original-body-${part}-down-0`);this.heroModel.add(i);this.heroParts[part]=i;}this.heroModel.setScale(1);this.updateHeroAppearance();this.animateHero(0,false);},
  setHeroDirection(dx,dy){this.heroDirection=Math.abs(dx)>Math.abs(dy)?'left':dy<0?'up':'down';this.heroFacing=dx>0?-1:1;for(const [part,s]of Object.entries(this.heroParts||{}))s.setTexture(`original-body-${part}-${this.heroDirection}-0`);},
  updateHeroAppearance(){if(!this.heroModel?.active)return;this.heroGear?.destroy();this.heroGear=null;for(const p of this.heroEquipment||[])p.destroy();this.heroEquipment=[];const p=state.profile;if(p.equipment.weapon){this.weaponVisual=this.add.image(11,0,this.itemTexture(p.equipment.weapon)).setScale(.55);this.heroModel.add(this.weaponVisual);this.heroEquipment.push(this.weaponVisual);}else this.weaponVisual=null;if(p.equipment.helmet){this.helmetVisual=this.add.image(0,-20,'original-helmet-0').setScale(.8);this.heroModel.add(this.helmetVisual);this.heroEquipment.push(this.helmetVisual);}else this.helmetVisual=null;this.heroParts?.torso?.setTint(p.equipment.armor?0xd7c7ad:0x736a61);},
  animateHero(time,moving){if(!this.heroParts)return;const phase=moving?Math.sin(time*11):0,bob=moving?Math.abs(phase)*1.1:Math.sin(time*2)*.35;const positions={head:[0,-21],torso:[0,-10],pelvis:[0,0],left_shoulder:[-8,-12],right_shoulder:[8,-12],left_upper_arm:[-9,-8],right_upper_arm:[9,-8],left_lower_arm:[-10,-2],right_lower_arm:[10,-2],left_upper_leg:[-4,7],right_upper_leg:[4,7],left_lower_leg:[-4,12],right_lower_leg:[4,12]};for(const [part,s]of Object.entries(this.heroParts)){const [x,y]=positions[part],sign=part.startsWith('left')?1:-1;s.setPosition(x,y+bob+(part.includes('leg')?phase*sign*2.5:part.includes('arm')?-phase*sign*1.8:0));s.setAngle(part.includes('leg')?phase*sign*12:part.includes('arm')?-phase*sign*10:0);}this.heroModel.setScale(this.heroDirection==='left'?(this.heroFacing||1):1,1);if(this.helmetVisual){this.helmetVisual.setTexture(this.heroDirection==='down'?'original-helmet-0':`original-helmet-${this.heroDirection}-0`).setPosition(0,-24+bob);}this.weaponVisual?.setPosition(13,-3+bob).setAngle(this.attackUntil>this.clock?Math.sin((this.attackUntil-this.clock)*12)*70:moving?phase*8:0);},
  update(time,delta){if(this.keys&&['W','A','S','D','UP','DOWN','LEFT','RIGHT'].some(k=>this.keys[k].isDown))this.pendingInteraction=null;baseUpdate.call(this,time,delta);if(!this.hero)return;
if(this.pendingInteraction&&!state.panel&&state.mode!=='result'){const o=this.pendingInteraction;if(Math.hypot(o.x-this.hero.x,o.y-this.hero.y)<(o.type==='walk'?5:70)){this.pendingInteraction=null;if(o.type!=='walk')this.interact(o);}else {const tx=Math.floor(this.hero.x/32),ty=Math.floor(this.hero.y/32);let best=this.interactionPath?.[ty]?.[tx]??Infinity,target={x:o.x,y:o.y};for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const n=this.interactionPath?.[ty+dy]?.[tx+dx]??Infinity;if(n<best){best=n;target={x:(tx+dx)*32+16,y:(ty+dy)*32+16};}}const a=Math.atan2(target.y-this.hero.y,target.x-this.hero.x);this.moveBody(this.hero,Math.cos(a)*165*Math.min(delta/1000,.05),Math.sin(a)*165*Math.min(delta/1000,.05));this.setHeroDirection(Math.cos(a),Math.sin(a));}}
this.animateHero(time/1000,!!this.pendingInteraction||!!(this.keys.W.isDown||this.keys.A.isDown||this.keys.S.isDown||this.keys.D.isDown||this.keys.UP.isDown||this.keys.DOWN.isDown||this.keys.LEFT.isDown||this.keys.RIGHT.isDown));for(const o of this.objects){const near=Math.hypot(o.x-this.hero.x,o.y-this.hero.y)<100,visible=state.mode!=='raid'||this.visibleTiles.has(Math.floor(o.y/32)*this.map.w+Math.floor(o.x/32));o.sprite?.setVisible(visible);o.label?.setVisible(visible&&near);}for(const e of this.enemies)e.sprite.setVisible(this.visibleTiles.has(Math.floor(e.sprite.y/32)*this.map.w+Math.floor(e.sprite.x/32)));if(state.mode==='hub')this.renderOverlay();},
 });
}
