import {effectiveSkillStats,skillStatLines} from './skill-stats.js';
import {consumeRaidMap,detachHeld} from './raid-maps.js';
import gearArt from './gear-art.json';
import {uiScaleFor,worldScaleFor} from './ui-metrics.js';
import {MERCHANTS,merchantStock} from './merchants.js';
import {toggleFullscreen} from './game-input.js';
import {drawOrbHUD,updateOrbHUD} from './orb-hud.js';
import {isActiveSkill} from './skill-rules.js';
import {ACTION_KEYS,actionSlots,assignAction} from './action-slots.js';
import Phaser from 'phaser';
import {mapContours} from './cartography.js';
import {dragCell,socketLayout} from './visual-layout.js';
import assets from './original-assets.json';
import { state, save, toast, openPanel, closePanel } from './main.js';
import { grid, put, fits, item, rollLoot, rng, flowField, RARITIES, DEFS, equippedSkills, starter, vendorPrice } from './core.js';
import { equip, equipFrom, unequip, socketGem, unsocket, transfer, moveCursorGem, placeCursorGem } from './inventory.js';

const textStyle = {fontFamily:'Arial, sans-serif',fontSize:'14px',color:'#d9c895',stroke:'#090709',strokeThickness:0,resolution:4};
const color = it => Phaser.Display.Color.HexStringToColor(RARITIES[it?.rarity || 0].color).color;
const slots = {weapon:[78,142,98,131],shield:[302,142,98,131],armor:[208,165,66,99],helmet:[208,66,66,67],gloves:[110,313,66,67],boots:[302,313,66,67],belt:[208,280,66,35],ring:[170,278,34,35],ring2:[280,278,34,35],amulet:[283,104,34,35]};
const original = (scene,key,n=0) => `original-${key}-${n}`;
export function preloadOriginal(scene) {
 scene.load.image('gothic-hud',`${import.meta.env.BASE_URL}assets/gothic-hud.png`);
  for(const [key,frames] of Object.entries(assets)) for(let n=0;n<frames.length;n++) scene.load.image(original(scene,key,n),`${import.meta.env.BASE_URL}assets/original/${frames[n].file}`);
}
function img(s,parent,x,y,key,w,h){const i=s.add.image(x,y,key).setOrigin(0); if(w) i.setDisplaySize(w,h);if(parent){parent.add(i);i.setScrollFactor(0);i.cameraFilter=s.cameras.main.id;}return i;}
function label(s,parent,x,y,value,size=14,col='#d9c895'){const t=s.add.text(x,y,value,{...textStyle,fontSize:`${Math.max(14,size)}px`,color:col});t.texture.setFilter(Phaser.Textures.FilterMode.LINEAR);if(parent){parent.add(t);t.setScrollFactor(0);t.cameraFilter=s.cameras.main.id;}return t;}
function icon(s,parent,x,y,it,maxW,maxH){
 const t=s.textures.get(s.itemTexture(it)).getSourceImage();
 const socketGem=maxW<=23&&maxH<=25;
 const scale=socketGem?Math.min(1,maxW/t.width,maxH/t.height):Math.min(1,(it.w*32-2)/t.width,(it.h*32-2)/t.height);
 const i=img(s,parent,Math.round(x),Math.round(y),s.itemTexture(it)).setOrigin(.5).setScale(scale);i.cameraFilter=s.cameras.main.id;return i;
}
function button(s,parent,x,y,w,title,action){const b=s.add.nineslice(x,y,'original-button-0',undefined,w,26,9,9,5,5).setOrigin(0).setInteractive({useHandCursor:false});parent.add(b);b.cameraFilter=s.cameras.main.id;label(s,parent,x+w/2,y+13,title,12).setOrigin(.5);b.on('pointerover',()=>b.setTint(0xffd5b0)).on('pointerout',()=>b.clearTint()).on('pointerdown',(_p,_x,_y,e)=>{e.stopPropagation();action();});return b;}
function frame(s,parent,x,y,w,h){const f=s.add.nineslice(x,y,'original-stash-0','plain',w,h,8,8,36,4).setOrigin(0);parent.add(f);f.setScrollFactor(0);f.cameraFilter=s.cameras.main.id;return f;}
const socketPositions=(count,w,h,it)=>{const iw=it?it.w*32:w,ih=it?it.h*32:h;return socketLayout(count,iw,ih).map(([x,y])=>[Math.round(x+(w-iw)/2),Math.round(y+(h-ih)/2)]);};
function lineOfSight(map,x0,y0,x1,y1){let dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1,e=dx+dy;for(let n=0;n<30;n++){if(x0===x1&&y0===y1)return true;if(!map.tiles[y0]?.[x0])return false;const e2=2*e;if(e2>=dy){e+=dy;x0+=sx;}if(e2<=dx){e+=dx;y0+=sy;}}return false;}

export function installPresentation(Scene) {
 const baseCreate=Scene.prototype.create, baseReset=Scene.prototype.resetWorld, baseUpdate=Scene.prototype.update, baseRaid=Scene.prototype.startRaid, baseInteract=Scene.prototype.interact,baseObject=Scene.prototype.addObject,basePortal=Scene.prototype.portal;
 Object.assign(Scene.prototype,{
  addObject(type,x,y,texture,title){if(type==='expedition')y=292;const o=baseObject.call(this,type,x,y,texture,title);if(texture?.startsWith('original-')&&o.sprite)o.sprite.setScale(['original-books-0','original-rack-0','original-bench-0','original-cage-0'].includes(texture)?.5:1);return o;},
  portal(x,y,color){if(state.mode==='hub')y=290;basePortal.call(this,x,y,color);this.add.rectangle(x,y-15,90,115,0xffffff,.001).setDepth(y+10).setInteractive({useHandCursor:false}).on('pointerdown',()=>{const o=this.objects.find(o=>Math.hypot(o.x-x,o.y-y)<50&&(o.type==='expedition'||o.type==='exit'));if(o)this.interact(o);});},
  create(){for(const [key,frames]of Object.entries(assets))if(key.startsWith('atk-')||key.startsWith('death-')||key==='fireball'||key==='slash')this.anims.create({key:`original-${key}`,frames:frames.map((f,n)=>({key:`original-${key}-${n}`})),frameRate:14,repeat:key==='fireball'||key==='slash'?-1:0});const tex=this.textures.get('original-inventory-3');tex.add('no-charms',0,40,0,388,640);tex.add('edge',0,40,0,8,640);tex.add('bottom',0,40,712,388,8);this.textures.get('original-atlas-back-0').add('region',0,12,12,1430,776);this.textures.get('original-hud-12').add('experience',0,106,37,254,24);this.textures.get('original-stash-0').add('plain',0,0,0,560,112);baseCreate.call(this);this.input.mouse.disableContextMenu();this.input.setTopOnly(true);this.input.on('pointermove',p=>this.updateDragPreview(p));this.input.on('pointerdown',(p,over)=>{if(state.panel||over.length||!p.leftButtonDown())return;const pos=this.cameras.main.getWorldPoint(p.x/this.uiScale,p.y/this.uiScale);if(this.map.tiles[Math.floor(pos.y/32)]?.[Math.floor(pos.x/32)]){this.pendingInteraction={type:'walk',x:pos.x,y:pos.y};this.interactionPath=flowField(this.map,Math.floor(pos.x/32),Math.floor(pos.y/32));}});this.input.on('pointerup',p=>{if(!this.held||Math.hypot(p.x/this.uiScale-p.downX/this.uiScale,p.y/this.uiScale-p.downY/this.uiScale)<6)return;if(state.panel==='expedition'&&this.mapSlot&&Math.abs(p.x/this.uiScale-this.mapSlot.x)<36&&Math.abs(p.y/this.uiScale-this.mapSlot.y)<36){this.insertRaidMap();return;}const socket=this.socketTargets?.find(t=>Math.hypot(p.x/this.uiScale-t.x,p.y/this.uiScale-t.y)<10);if(socket&&['skill','support'].includes(this.held.it.kind)){this.handleSocket(socket.it,socket.index,p);return;}const t=this.gridTargets.find(t=>p.x/this.uiScale>=t.x&&p.y/this.uiScale>=t.y&&p.x/this.uiScale<t.x+t.g.w*t.cell&&p.y/this.uiScale<t.y+t.g.h*t.cell);if(t){const c=dragCell(t,this.held,p.x/this.uiScale,p.y/this.uiScale);this.placeHeld(t,c.x,c.y);}else if(this.panelKind==='vendor'&&p.x/this.uiScale>=this.sidePanelX&&p.x/this.uiScale<this.sidePanelX+396)this.sellHeld();else for(const [slot,[x,y,w,h]]of Object.entries(slots)){if(p.x/this.uiScale>=this.panelX+x&&p.x/this.uiScale<this.panelX+x+w&&p.y/this.uiScale>=y&&p.y/this.uiScale<y+h){const gear=state.profile.equipment[slot];if(['skill','support'].includes(this.held.it.kind)&&gear){const i=socketPositions(gear.sockets.length,w,h,gear).findIndex(([sx,sy])=>Math.hypot(p.x/this.uiScale-this.panelX-x-sx,p.y/this.uiScale-y-sy)<16);if(i>=0)this.handleSocket(gear,i,p);}else if(((this.held.it.slot||this.held.it.kind)===slot||this.held.it.slot==='ring'&&slot==='ring2'))this.equipHeld(slot);break;}}if(this.held){const ux=p.x/this.uiScale,uy=p.y/this.uiScale,inBag=ux>=this.panelX+40&&ux<this.panelX+436&&uy<640,inSide=state.panel!=='inventory'&&ux>=this.sidePanelX&&ux<this.sidePanelX+(this.sidePanelWidth||396)&&uy<640;if(!inBag&&!inSide)this.dropHeldItem();}});},
  resetWorld(){this.ui=null;this.canvasPanel=null;this.canvasDetail=null;this.tooltip=null;this.held=null;this.heldIcon=null;this.fog=null;this.explored=new Set();this.visibleTiles=new Set();this.fogStamp=-1;this.solidProps=[];this.pendingInteraction=null;baseReset.call(this);},
  itemTexture(it){if(it.kind==='map')return 'original-map-item-0';const choices=gearArt[it.slot||it.weapon||it.type];if(!it.visualSprite&&choices?.length&&it.id){const hash=[...it.id].reduce((h,c)=>(h*31+c.charCodeAt(0))>>>0,0);return `original-${choices[hash%choices.length]}-0`;}if(it.visualSprite&&assets[it.visualSprite])return `original-${it.visualSprite}-0`;if(assets['skill-icon-'+it.type])return `original-skill-icon-${it.type}-0`;const aliases={warstaff:'staff',longsword:'sword',hunterbow:'bow',plate:'armor',swiftboots:'boots',lifering:'ring'};if(aliases[it.type])return this.itemTexture({...it,type:aliases[it.type]});const gems={fire:'ruby',arrow:'emerald',slash:'topaz',nova:'sapphire',multi:'moon',haste:'emerald',pierce:'topaz',meteor:'ruby',rain:'emerald',juggernaut:'topaz',healing:'moon',blink:'sapphire',duration:'moon'};if(gems[it.type])return `original-${gems[it.type]}-0`;if(['staff','bow','armor'].includes(it.type))return `original-${it.type}-0`;if(it.type==='sword')return 'original-weapon-0';if(assets['item-'+it.type])return `original-item-${it.type}-0`;return it.icon==='coin'?'hs-coin-0':`${it.icon}-0`;},
  createCanvasHud(){this.ui=this.add.container(0,0).setDepth(10000).setScrollFactor(0);this.uiTexts={};this.uiMode=null;this.renderOverlay(true);},
  renderOverlay(force=false){if(!this.ui?.active)return;if(force||this.uiMode!==state.mode){this.ui.removeAll(true);this.uiMode=state.mode;this.uiTexts={};drawOrbHUD(this);this.updateHeroAppearance();this.markUI(this.ui);}updateOrbHUD(this);this.drawMinimap();},
  openActionPicker(index){
   if(state.panel&&state.panel!=='inventory'||state.mode==='result')return;
   this.actionPicker?.destroy();const options=[null,...equippedSkills(state.profile.equipment).filter(isActiveSkill)],cols=Math.min(5,options.length),height=24+Math.ceil(options.length/5)*52,width=24+cols*52;
   const menu=this.actionPicker=this.add.container(Math.round((this.uiWidth-width)/2),this.uiHeight-145-height).setDepth(12500);frame(this,menu,0,0,width,height);
   options.forEach((skill,i)=>{const x=12+i%5*52,y=12+Math.floor(i/5)*52;const choice=img(this,menu,x,y,'hs-skill-frame-0',46,46).setInteractive();choice.skillChoice=skill?.id||null;
    img(this,menu,x+4,y+4,skill?`original-skill-icon-${skill.type}-0`:'hs-button-close-0',38,38);
    choice.on('pointerover',p=>{if(skill)this.showItemTooltip(skill,p.x/this.uiScale,p.y/this.uiScale);}).on('pointerout',()=>{this.tooltip?.destroy();this.tooltip=null;}).on('pointerdown',(_p,_x,_y,e)=>{e.stopPropagation();assignAction(state.profile,index,skill?.id||null);save();menu.destroy();this.tooltip?.destroy();this.renderOverlay(true);});
   });this.markUI(menu);
  },
  drawMinimap(){
   if(!this.hudMap||!this.hero)return;
   const hub=state.mode==='hub',expanded=this.mapExpanded,tx=Math.floor(this.hero.x/32),ty=Math.floor(this.hero.y/32),stamp=[expanded,hub,tx,ty,this.explored.size,Math.floor((this.clock||0)*5)].join(':');if(stamp===this.mapStamp)return;this.mapStamp=stamp;
   const g=this.hudMap,edges=mapContours(this.map,this.explored,hub);g.clear();this.mapFrame?.setVisible(!expanded);
   let step,ox,oy;
   if(expanded){const w=hub?48:this.map.w,h=hub?38:this.map.h,cx=hub?48:this.map.w/2,cy=hub?43:this.map.h/2;step=Math.min((this.uiWidth-140)/w,(this.uiHeight-130)/h);ox=this.uiWidth/2-cx*step;oy=this.uiHeight/2-cy*step;g.fillStyle(0x07060b,.68).fillRect(0,0,this.uiWidth,this.uiHeight);}
   else {step=hub?Math.min(140/48,140/38):2.6;ox=this.uiWidth-84-(hub?48:tx)*step;oy=85-(hub?43:ty)*step;}
   const inView=(x,y)=>expanded||x>=this.uiWidth-153&&x<=this.uiWidth-15&&y>=15&&y<=153;
   g.lineStyle(1,0x8995b6,expanded?.85:.8);for(const [x1,y1,x2,y2]of edges){const ax=ox+x1*step,ay=oy+y1*step,bx=ox+x2*step,by=oy+y2*step;if(inView(ax,ay)&&inView(bx,by))g.lineBetween(Math.round(ax),Math.round(ay),Math.round(bx),Math.round(by));}
   if(hub){g.lineStyle(1,0x706b7d,.8);for(const p of this.solidProps.filter(p=>p.w>60&&p.h>30)){const x=ox+p.x/32*step,y=oy+p.y/32*step,w=p.w/32*step,h=p.h/32*step;if(inView(x,y)&&inView(x+w,y+h))g.strokeRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h));}}
   for(const o of this.objects){if(!['stash','vendor','exit','expedition','container','rune','pickup'].includes(o.type))continue;const x=ox+o.x/32*step,y=oy+o.y/32*step;if(!inView(x,y)||!hub&&!this.explored.has(Math.floor(o.y/32)*this.map.w+Math.floor(o.x/32)))continue;g.fillStyle(['exit','expedition'].includes(o.type)?0x31d9e6:o.type==='rune'?0x9a7be7:o.type==='container'?0xb69452:0xd8b574).fillRect(Math.round(x)-2,Math.round(y)-2,4,4);}
   for(const e of this.enemies||[]){const s=e.sprite,id=Math.floor(s.y/32)*this.map.w+Math.floor(s.x/32),x=ox+s.x/32*step,y=oy+s.y/32*step;if(e.hp>0&&this.visibleTiles.has(id)&&inView(x,y))g.fillStyle(0xdb4a43).fillCircle(Math.round(x),Math.round(y),2);}
   const x=ox+this.hero.x/32*step,y=oy+this.hero.y/32*step;g.fillStyle(0xf5eee0).fillTriangle(x,y-3,x-3,y+3,x+3,y+3);
  },
  setInteractionText(t){this.uiTexts?.hint?.setText(t);},
  toastCanvas(message){if(!this.ui?.active)return;this.toastObject?.destroy();this.toastObject=label(this,this.ui,this.uiWidth/2,90,message,14).setOrigin(.5);const t=this.toastObject;this.time.delayedCall(3500,()=>t.active&&t.destroy());},
  closeCanvasPanel(){this.tooltip?.destroy();this.tooltip=null;this.heldIcon?.destroy();this.heldIcon=null;this.dragPreview?.destroy();this.dragPreview=null;this.held=null;this.searchFill=null;this.searchItemFill=null;this.canvasPanel?.destroy();this.canvasPanel=null;},
  openCanvasPanel(panel,search=state.search){this.actionPicker?.destroy();this.pendingInteraction=null;this.mapExpanded=false;this.mapStamp=null;this.closeCanvasPanel();this.panelKind=panel;this.lastItemClick=null;this.canvasPanel=this.add.container(0,0).setScrollFactor(0).setDepth(11000);const parent=this.canvasPanel;
   this.sidePanelX=Math.max(0,Math.min(220,Math.floor((this.uiWidth-1240)/4)));this.panelX=this.uiWidth-436-this.sidePanelX;this.panelY=0;this.sidePanelWidth=396;this.gridTargets=[];this.socketTargets=[];
   const inventory=['inventory','stash','container','vendor','expedition'].includes(panel);
   if(inventory){parent.add(this.add.image(this.panelX+40,0,'original-inventory-3','no-charms').setOrigin(0));parent.add(this.add.image(this.panelX+428,0,'original-inventory-3','edge').setOrigin(0).setFlipX(true));parent.add(this.add.image(this.panelX+40,632,'original-inventory-3','bottom').setOrigin(0));const blocker=this.add.zone(this.panelX+40,0,396,640).setOrigin(0).setInteractive();parent.addAt(blocker,0);label(this,parent,this.panelX+238,12,'ИНВЕНТАРЬ',18).setOrigin(.5,0);
    this.drawCanvasEquipment(this.panelX,0);this.drawCanvasGrid(state.profile.bag,this.panelX+46,425,'bag',Infinity,32);
    this.drawCurrency(parent,this.panelX+60,604);
    if(panel!=='inventory')this.drawSidePanel(panel,search);
   }else{this.panelX=Math.floor((this.uiWidth-460)/2)-40;const mh=panel==='pause'?230:panel==='result'?300:360;this.modalTop=Math.floor((this.uiHeight-mh)/2);frame(this,parent,this.panelX+40,this.modalTop,460,mh);const blocker=this.add.zone(0,0,this.uiWidth,this.uiHeight).setOrigin(0).setInteractive();parent.addAt(blocker,0);label(this,parent,this.panelX+270,this.modalTop+22,{expedition:'ЭКСПЕДИЦИЯ',pause:'ПАУЗА',help:'ПАМЯТКА',result:'ИТОГ ВЫЛАЗКИ',destroy:'УНИЧТОЖИТЬ ПРЕДМЕТ?'}[panel]||panel,20).setOrigin(.5,0);if(panel==='expedition')this.drawCanvasExpedition();else if(panel==='result')this.drawCanvasResult();else if(panel==='destroy')this.drawDiscardConfirm();else this.drawCanvasHelp();}
   if(panel!=='result'){const close=img(this,parent,this.panelX+48,inventory?8:this.modalTop+12,'hs-button-close-0',22,22).setInteractive();close.on('pointerdown',()=>{if(panel==='destroy')this.confirmDiscard(false);else closePanel();});}this.markUI(parent);
  },
  drawCanvasGrid(g,x,y,source,revealed=Infinity,cell=32){const parent=this.canvasPanel;const target={g,x,y,cell,source};this.gridTargets.push(target);
   for(let yy=0;yy<g.h;yy++)for(let xx=0;xx<g.w;xx++){const tile=img(this,parent,x+xx*cell,y+yy*cell,'original-cell-0',cell,cell).setInteractive();tile.on('pointerdown',(p,_x,_y,e)=>{e.stopPropagation();if(this.held)this.placeHeld(target,xx-(this.held.grabX||0),yy-(this.held.grabY||0));});}
   g.items.forEach((it,index)=>{const px=x+it.x*cell,py=y+it.y*cell,hidden=index>=revealed;const zone=this.add.rectangle(px,py,it.w*cell,it.h*cell,0xffffff,.001).setOrigin(0).setInteractive({useHandCursor:false});parent.add(zone);zone.itemHitId=it.id;
    if(hidden){label(this,parent,px+it.w*cell/2,py+it.h*cell/2,index===revealed?'⋯':'?',20,'#776952').setOrigin(.5);if(index===revealed){img(this,parent,px+3,py+it.h*cell-10,'original-identify-0',it.w*cell-6,6);this.searchItemFill=this.add.rectangle(px+5,py+it.h*cell-8,it.w*cell-10,2,0xc6ab69).setOrigin(0);parent.add(this.searchItemFill);}return;}
    const back=img(this,parent,px+1,py+1,'original-slot-background-0',it.w*cell-2,it.h*cell-2).setAlpha(.72);back.itemId=it.id;const art=icon(this,parent,px+it.w*cell/2,py+it.h*cell/2,it,it.w*cell-4,it.h*cell-4);art.itemId=it.id;this.drawItemSockets(parent,it,px,py,it.w*cell,it.h*cell,['bag','stash'].includes(source));
    zone.on('pointerover',p=>this.showItemTooltip(it,p.x/this.uiScale,p.y/this.uiScale));zone.on('pointerout',()=>{this.tooltip?.destroy();this.tooltip=null;});zone.on('pointerdown',(p,_x,_y,e)=>{e.stopPropagation();if(this.held){const c=dragCell(target,this.held,p.x/this.uiScale,p.y/this.uiScale);this.placeHeld(target,c.x,c.y);return;}if(p.rightButtonDown()){if(p.event?.ctrlKey){this.quickTransfer(it,source);return;}if(['bag','stash','container'].includes(source)&&['armor','weapon'].includes(it.kind))this.inventoryAction(()=>equipFrom(state.profile,g,it.id,undefined,state.search));return;}
     if(p.event?.shiftKey){this.quickTransfer(it,source);this.lastItemClick=null;return;}this.lastItemClick={id:it.id,time:p.downTime};this.beginItemDrag({it,source,g,grabX:Math.floor((p.x/this.uiScale-px)/cell),grabY:Math.floor((p.y/this.uiScale-py)/cell)},p);
    });
   });return target;
  },

  beginItemDrag(held,pointer){
   held.grabX??=Math.floor(held.it.w/2);held.grabY??=Math.floor(held.it.h/2);this.held=held;this.tooltip?.destroy();this.tooltip=null;
   this.heldIcon=this.add.container(0,0).setDepth(14000).setScrollFactor(0);const {it}=held,w=it.w*32,h=it.h*32;
   icon(this,this.heldIcon,w/2,h/2,it,w-4,h-4);this.drawItemSockets(this.heldIcon,it,0,0,w,h);this.markUI(this.heldIcon);
   this.dragPreview=this.add.graphics().setDepth(13900).setScrollFactor(0);this.dragPreview.cameraFilter=this.cameras.main.id;
   for(const child of this.canvasPanel.list)if(child.itemId===it.id||child.gearId===it.id)child.setVisible(false);
   this.updateDragPreview(pointer);
  },
  updateDragPreview(p){
   if(!this.heldIcon||!this.held)return;const px=p.x/this.uiScale,py=p.y/this.uiScale,h=this.held;
   this.heldIcon.setPosition(Math.round(px-(h.grabX||0)*32-16),Math.round(py-(h.grabY||0)*32-16));this.dragPreview.clear();
   const t=this.gridTargets.find(t=>px>=t.x&&py>=t.y&&px<t.x+t.g.w*t.cell&&py<t.y+t.g.h*t.cell);if(!t)return;
   const c=dragCell(t,h,px,py),trade=t.source==='vendor'&&h.source==='bag';
   const allowed=trade||fits(t.g,h.it,c.x,c.y,h.g===t.g?h.it.id:undefined)&&(h.source!=='vendor'||t.source==='bag'&&state.profile.gold>=vendorPrice(h.it))&&(h.source!=='equipment'||t.source==='bag');
   for(let y=0;y<h.it.h;y++)for(let x=0;x<h.it.w;x++){const tx=c.x+x,ty=c.y+y;if(tx>=0&&ty>=0&&tx<t.g.w&&ty<t.g.h)this.dragPreview.fillStyle(allowed?0x248b37:0x9d2534,.7).fillRect(t.x+tx*t.cell+2,t.y+ty*t.cell+2,t.cell-3,t.cell-3);}
  },
  drawItemSockets(parent,it,x,y,w,h,interactive=false){
   const points=socketPositions(it.sockets?.length||0,w,h,it);if(!points.length)return;this.socketViews ||= [];const root=parent,full=this.add.container(0,0);root.add(full);full.itemId=it.id;parent=full;
   const links=this.add.graphics().lineStyle(4,0x34291e);for(let i=1;i<points.length;i++)if(it.links?.[i-1]!==false)links.lineBetween(x+points[i-1][0],y+points[i-1][1],x+points[i][0],y+points[i][1]);links.lineStyle(2,0xb9a477);for(let i=1;i<points.length;i++)if(it.links?.[i-1]!==false)links.lineBetween(x+points[i-1][0],y+points[i-1][1],x+points[i][0],y+points[i][1]);links.itemId=it.id;parent.add(links);
   points.forEach(([sx,sy],index)=>{const gx=x+sx,gy=y+sy,ring=img(this,parent,gx-10,gy-10,'original-socket-ring-0');ring.itemId=it.id;const gem=it.sockets[index];if(gem){const art=icon(this,parent,gx,gy,gem,20,20);art.itemId=gem.id;art.gearId=it.id;}
    if(interactive){this.socketTargets.push({it,index,x:gx,y:gy});ring.setInteractive().on('pointerover',p=>{if(gem)this.showItemTooltip(gem,p.x/this.uiScale,p.y/this.uiScale,it);}).on('pointerout',()=>{this.tooltip?.destroy();this.tooltip=null;}).on('pointerdown',(p,_x,_y,e)=>{e.stopPropagation();if(!p.rightButtonDown()&&(!this.held||!['skill','support'].includes(this.held.it.kind))||p.event?.ctrlKey){root.list.find(o=>o.itemHitId===it.id)?.emit('pointerdown',p,_x,_y,e);return;}this.handleSocket(it,index,p);});}
   });
   const mask=this.add.graphics();mask.itemId=it.id;root.add(mask);const mini=socketLayout(points.length,it.w*32,it.h*32).map(([sx,sy])=>[x+w/2+(sx-it.w*16)*.3,y+h-8+(sy-it.h*16)*.3]);mask.lineStyle(1,0xc2ae78,.85);for(let i=1;i<mini.length;i++)if(it.links?.[i-1]!==false)mask.lineBetween(...mini[i-1],...mini[i]);const hues={fire:0xf25639,meteor:0xf25639,slash:0xf4cd52,juggernaut:0xf4cd52,arrow:0x61d352,rain:0x61d352,nova:0x5fbcef,blink:0x5fbcef,healing:0xf3efdb,haste:0x61d352,pierce:0xf4cd52,multi:0xf3efdb,duration:0xf3efdb};mini.forEach(([mx,my],i)=>{mask.fillStyle(it.sockets[i]?hues[it.sockets[i].type]||0xa899f1:0x28252c).fillCircle(mx,my,3).lineStyle(1,0x9d906c).strokeCircle(mx,my,3);});this.markUI(full);this.socketViews.push({full,mask,root,itemId:it.id});this.updateSocketVisibility();
  },
  updateSocketVisibility(){const detailed=!!this.keys?.ALT.isDown||['skill','support'].includes(this.held?.it.kind);this.socketViews=(this.socketViews||[]).filter(v=>v.full.active&&v.mask.active);for(const {full,mask,root,itemId}of this.socketViews){const moving=this.held?.it.id===itemId&&root!==this.heldIcon;full.setVisible(!moving&&detailed);mask.setVisible(!moving&&!detailed);}},
  handleSocket(gear,index,pointer){
   if(this.held){const result=moveCursorGem(state.profile,gear,index,this.held);if(!result)return;save();this.renderOverlay(true);this.openCanvasPanel(state.panel,state.search);if(result.held)this.beginItemDrag(result.held,pointer);}
   else if(pointer.rightButtonDown()&&gear.sockets[index])this.beginItemDrag({it:gear.sockets[index],source:'socket',gear,index,grabX:0,grabY:0},pointer);
  },
  equipHeld(slot){const h=this.held;if(!h||!['bag','stash','container'].includes(h.source))return;this.inventoryAction(()=>equipFrom(state.profile,h.g,h.it.id,slot,state.search));},
  inventoryAction(fn){if(!fn())return toast('Недостаточно места или несовместимый предмет');save();this.renderOverlay(true);this.openCanvasPanel(state.panel,state.search);},
  placeHeld(target,x,y){const h=this.held;if(!h)return;if(h.source==='socket'){if(!['bag','stash'].includes(target.source))return;this.inventoryAction(()=>placeCursorGem(h,target.g,x,y));}else if(h.source==='equipment'){if(target.source!=='bag')return;this.inventoryAction(()=>{if(!put(target.g,h.it,x,y))return false;state.profile.equipment[h.slot]=null;return true;});}else if(h.source==='vendor'){if(target.source!=='bag')return;this.inventoryAction(()=>{const price=vendorPrice(h.it);if(state.profile.gold<price||!transfer(h.g,target.g,h.it.id,null,x,y))return false;state.profile.gold-=price;return true;});}else if(target.source==='vendor')this.sellHeld();else this.inventoryAction(()=>transfer(h.g,target.g,h.it.id,state.search,x,y));},
  sellHeld(){if(this.held?.source!=='bag')return;const it=this.held.it;this.inventoryAction(()=>{state.profile.bag.items=state.profile.bag.items.filter(i=>i.id!==it.id);state.profile.gold+=it.free?0:it.value;put(this.vendorStock,it);return true;});},
  quickTransfer(it,source){if(source==='vendor'){this.held={it,source,g:this.vendorStock};return this.placeHeld({source:'bag',g:state.profile.bag});}let from=source==='bag'?state.profile.bag:source==='stash'?state.profile.stash:state.search?.grid;let to=source==='bag'?(state.panel==='stash'?state.profile.stash:state.panel==='container'?state.search?.grid:null):state.profile.bag;
   if(state.panel==='vendor'&&source==='bag'){state.profile.bag.items=state.profile.bag.items.filter(i=>i.id!==it.id);state.profile.gold+=it.free?0:it.value;save();this.renderOverlay(true);this.openCanvasPanel('vendor');return;}
   if(!to)return this.inventoryAction(()=>equip(state.profile,it.id));this.inventoryAction(()=>transfer(from,to,it.id,state.search));
  },
  drawCanvasEquipment(x,y){const parent=this.canvasPanel,p=state.profile;for(const [slot,[sx,sy,w,h]] of Object.entries(slots)){const it=p.equipment[slot],quality=['normal','normal','rare','satanic'][it?.rarity||0],backType=slot==='weapon'||slot==='shield'?'weapon':slot==='armor'?'armor':['helmet','gloves','boots'].includes(slot)?'helmet':slot==='belt'?'belt':'jewelry';img(this,parent,x+sx,y+sy,`original-slot-${slot==='ring2'?'ring':slot}-0`);if(it)img(this,parent,x+sx+(backType==='jewelry'?1:3),y+sy+(backType==='jewelry'?1:3),`original-equip-${backType}-${quality}-0`);const z=this.add.rectangle(x+sx,y+sy,w,h,0xffffff,.001).setOrigin(0).setInteractive({useHandCursor:false});parent.add(z);if(it)z.itemHitId=it.id;
    if(it){const art=icon(this,parent,x+sx+w/2,y+sy+h/2,it,w-12,h-12);art.itemId=it.id;}
    z.on('pointerover',p=>{if(it)this.showItemTooltip(it,p.x/this.uiScale,p.y/this.uiScale);});z.on('pointerout',()=>{this.tooltip?.destroy();this.tooltip=null;});z.on('pointerdown',(pointer,_x,_y,e)=>{e.stopPropagation();if(this.held){const h=this.held;if(['bag','stash','container'].includes(h.source)&&((h.it.slot||h.it.kind)===slot||h.it.slot==='ring'&&slot==='ring2'))this.equipHeld(slot);else toast('Этот предмет не подходит в выбранный слот');}else if(it&&pointer.rightButtonDown())this.inventoryAction(()=>unequip(p,slot));else if(it){this.beginItemDrag({it,source:'equipment',slot},pointer);}});
    if(it)this.drawItemSockets(parent,it,x+sx,y+sy,w,h,true);
   }},
  showSkillTooltip(it,px,py){
   if(this.held)return;this.tooltip?.destroy();const equipped=equippedSkills(state.profile.equipment).find(g=>g.id===it.id),skill=equipped||{...it,supports:[]};
   const stats=effectiveSkillStats(skill,this.skillBonuses[it.id],this.damage(skill),Object.values(state.profile.equipment).reduce((n,g)=>n+(g?.healingBonus||0),0));
   const lines=skillStatLines(skill,stats),width=340,x=Math.max(8,Math.min(this.uiWidth-width-8,px-width-18));
   const p=this.tooltip=this.add.container(x,0).setDepth(13500);
   icon(this,p,34,34,it,40,40);label(this,p,64,19,it.name,18,RARITIES[it.rarity].color);const desc=label(this,p,18,65,it.description||'',14,'#c3b69f').setWordWrapWidth(width-36);
   const body=label(this,p,18,Math.max(96,desc.y+desc.height+16),lines.join('\n'),14,'#e9dfc8').setLineSpacing(5).setWordWrapWidth(width-36);const height=body.y+body.height+(equipped?22:48);
   if(!equipped)label(this,p,18,height-27,'Не установлено · без связанных поддержек',12,'#9b8c76');p.addAt(this.add.rectangle(0,0,width,height,0x080709,.98).setOrigin(0).setStrokeStyle(1,0x9c875e),0);p.setY(Math.max(8,Math.min(this.uiHeight-height-8,py-height/2)));this.markUI(p);
  },
  showItemTooltip(it,px,py,gear){if(this.held)return;if(it.kind==='skill')return this.showSkillTooltip(it,px,py);this.tooltip?.destroy();const width=300,height=it.sockets?245:185;const x=Math.max(8,Math.min((this.panelX??this.uiWidth/2+width/2)-width+30,px-width-16)),y=Math.min(this.uiHeight-height-8,Math.max(12,py-40));this.tooltip=this.add.container(x,y).setScrollFactor(0).setDepth(13500);const bg=this.add.rectangle(0,0,width,height,0x050405,.97).setOrigin(0).setStrokeStyle(1,0x827443);this.tooltip.add(bg);label(this,this.tooltip,150,16,it.name,17,RARITIES[it.rarity].color).setOrigin(.5);label(this,this.tooltip,150,42,RARITIES[it.rarity].name,12).setOrigin(.5);const desc=it.damage?`Урон: ${Math.round(it.damage*RARITIES[it.rarity].mult)}\nТип оружия: ${it.weapon}`:it.armor?`Броня: +${Math.round(it.armor*RARITIES[it.rarity].mult)}`:it.description||'Добыча из подземелья';label(this,this.tooltip,18,72,desc+(it.movement?'\nСкорость: +'+Math.round(it.movement*100)+'%':'')+(it.healingBonus?'\nИсцеление: +'+Math.round(it.healingBonus*100)+'%':''),13,'#c4c4bf').setWordWrapWidth(264);if(it.sockets){label(this,this.tooltip,18,126,`Сокеты: ${it.sockets.filter(Boolean).length} / ${it.sockets.length}`,13);it.sockets.forEach((g,i)=>{img(this,this.tooltip,18+i*38,154,'original-socket-0',28,28);if(g)icon(this,this.tooltip,32+i*38,168,g,23,25);});label(this,this.tooltip,18,193,'Поддержки действуют по цепочке связей.',11);}this.markUI(this.tooltip);label(this,this.tooltip,18,height-28,`${state.panel==='vendor'&&this.vendorStock?.items.includes(it)?'Покупка':'Продажа'}: ${it.free?0:state.panel==='vendor'&&this.vendorStock?.items.includes(it)?vendorPrice(it):it.value} золота`,12,'#c6ad62');},
  drawSidePanel(panel,search){if(panel==='expedition'){this.drawCanvasExpedition();return;}const x=this.sidePanelX,parent=this.canvasPanel;frame(this,parent,x,0,396,640);const blocker=this.add.rectangle(x,0,396,640,0xffffff,.001).setOrigin(0).setInteractive();parent.addAt(blocker,0);blocker.on('pointerdown',()=>{if(panel==='vendor')this.sellHeld();});label(this,parent,x+198,14,panel==='stash'?'ТАЙНИК':panel==='vendor'?(MERCHANTS[this.activeVendor?.merchantId||'jeweler'].title):search?.title||'ОБЫСК',18).setOrigin(.5,0);
   if(panel==='stash')this.drawCanvasGrid(state.profile.stash,x+38,88,'stash');
   if(panel==='container'&&search){const gx=x+(396-search.grid.w*32)/2;this.drawCanvasGrid(search.grid,gx,110,'container',search.revealed,32);label(this,parent,x+198,78,search.revealed<search.grid.items.length?'ОБЫСК':'ОБЫСК ЗАВЕРШЁН',12).setOrigin(.5);this.searchFill=this.add.rectangle(gx,110+search.grid.h*32+14,search.grid.w*32,3,0xc6ab69).setOrigin(0);parent.add(this.searchFill);button(this,parent,x+98,620,200,'Забрать всё',()=>{for(const it of [...search.grid.items.slice(0,search.revealed)])transfer(search.grid,state.profile.bag,it.id,search);save();this.openCanvasPanel('container',search);});}
   if(panel==='vendor'){this.vendorStocks ||= {};this.vendorStock=merchantStock(this.vendorStocks,this.activeVendor?.merchantId);this.drawCanvasGrid(this.vendorStock,x+6,88,'vendor');label(this,parent,x+26,610,`${state.profile.gold} золота`,14);if(!Object.values(state.profile.equipment).some(i=>i?.kind==='weapon')&&![...state.profile.bag.items,...state.profile.stash.items].some(i=>i.kind==='weapon'))button(this,parent,x+48,570,300,'Бесплатный походный комплект',()=>{Object.assign(state.profile.equipment,starter());save();this.renderOverlay(true);this.openCanvasPanel('vendor');});}
  },
  refreshCanvasSearch(){if(state.panel==='container'&&!this.held)this.openCanvasPanel('container',state.search);},
  drawCurrency(parent,x,y){img(this,parent,x,y,'original-button-0',160,28);img(this,parent,x+10,y+5,'hs-coin-0',20,18);label(this,parent,x+145,y+14,String(state.profile.gold),15,'#e4c86d').setOrigin(1,.5);},
  spawnGroundItem(it,x=this.hero.x,y=this.hero.y){const o=this.addObject('pickup',x,y,this.groundItemTexture(it),it.name);o.item=it;o.sprite.setScale(.65);return o;},
  groundItemTexture(it){if(['skill','support'].includes(it.kind)){const gems={fire:'ruby',meteor:'ruby',arrow:'emerald',rain:'emerald',haste:'emerald',nova:'sapphire',blink:'sapphire',slash:'topaz',juggernaut:'topaz',pierce:'topaz'};return `original-${gems[it.type]||'moon'}-0`;}return this.itemTexture(it);},
  outsideItemPanels(p){const x=p.x/this.uiScale,y=p.y/this.uiScale;return ['inventory','stash','container','vendor','expedition'].includes(state.panel)&&!(x>=this.panelX+40&&x<this.panelX+436&&y>=0&&y<640)&&!(state.panel!=='inventory'&&x>=this.sidePanelX&&x<this.sidePanelX+(this.sidePanelWidth||396)&&y>=0&&y<640);},
  dropHeldItem(){if(!this.held||this.held.source==='vendor')return;const held=this.held,search=state.search;
   if(state.mode==='hub'){this.pendingDiscard={held,search,panel:state.panel};openPanel('destroy');return;}
   if(state.mode!=='raid')return;const it=detachHeld(state.profile,held,search);if(!it)return;this.spawnGroundItem(it);save();this.renderOverlay(true);this.openCanvasPanel(state.panel,search);
  },
  drawDiscardConfirm(){const x=this.panelX+70,y=this.modalTop,p=this.canvasPanel,it=this.pendingDiscard?.held.it;if(!it)return;icon(this,p,x+200,y+95,it,64,80);label(this,p,x+200,y+156,it.name,18).setOrigin(.5);label(this,p,x+200,y+195,'В убежище выброшенный предмет исчезнет.',14).setOrigin(.5);button(this,p,x+15,y+260,180,'Уничтожить',()=>this.confirmDiscard(true));button(this,p,x+220,y+260,180,'Отмена',()=>this.confirmDiscard(false));},
  confirmDiscard(accept){const pending=this.pendingDiscard;if(!pending)return;if(accept)detachHeld(state.profile,pending.held,pending.search);this.pendingDiscard=null;save();this.renderOverlay(true);openPanel(pending.panel,pending.search);},
  insertRaidMap(){if(this.held?.source!=='bag'||this.held.it.kind!=='map')return;this.selectedMapId=this.held.it.id;this.openCanvasPanel('expedition');},
  launchSelectedMap(){const map=consumeRaidMap(state.profile,this.selectedMapId);if(!map)return toast('Вставьте карту из рюкзака');this.selectedMapId=null;this.pendingRaidMap=map;state.mode='raid';state.profile.inRaid=true;state.profile.runs++;save();closePanel();this.startRaid();},
  drawCanvasExpedition(){
   const x=this.sidePanelX,p=this.canvasPanel,w=this.panelX+26-x;this.sidePanelWidth=w;frame(this,p,x,0,w,640);p.addAt(this.add.zone(x,0,w,640).setOrigin(0).setInteractive(),0);
   label(this,p,x+w/2,18,'АТЛАС',22).setOrigin(.5,0);
   const terrain=this.add.image(x+14,62,'original-atlas-back-0','region').setOrigin(0).setDisplaySize(w-28,350);p.add(terrain);
   const town={x:x+w*.24,y:318},forest={x:x+w*.7,y:194};
   const line=this.add.graphics().lineStyle(5,0x171218,.85).lineBetween(town.x,town.y,forest.x,forest.y).lineStyle(2,0xc8b180,.95).lineBetween(town.x,town.y,forest.x,forest.y);p.add(line);
   for(let n=1;n<8;n++){const t=n/8;img(this,p,town.x+(forest.x-town.x)*t-4,town.y+(forest.y-town.y)*t-3,'original-atlas-link-0',8,6);}
   img(this,p,town.x-17,town.y-17,'original-atlas-town-0',34,34);label(this,p,town.x,town.y+27,'Убежище',15).setOrigin(.5);
   img(this,p,forest.x-24,forest.y-24,'original-atlas-selected-0',48,48);const node=img(this,p,forest.x-18,forest.y-18,'original-atlas-node-0',36,36).setInteractive();node.on('pointerdown',()=>{this.atlasSelected=true;this.openCanvasPanel('expedition');});
   label(this,p,forest.x,forest.y+37,'Проклятый лес',17).setOrigin(.5);label(this,p,forest.x,forest.y+58,'10 минут · доступно',13).setOrigin(.5);
   const map=state.profile.bag.items.find(it=>it.id===this.selectedMapId&&it.kind==='map');
   p.add(this.add.rectangle(x+16,432,w-32,123,0x0b090b,.96).setOrigin(0).setStrokeStyle(1,0x655139));
   this.mapSlot={x:x+66,y:489};const slot=img(this,p,x+30,453,'hs-skill-frame-0',72,72).setInteractive();slot.on('pointerdown',(pointer,_x,_y,event)=>{event.stopPropagation();if(pointer.rightButtonDown()){this.selectedMapId=null;this.openCanvasPanel('expedition');}else this.insertRaidMap();});
   if(map)img(this,p,x+46,467,'original-map-item-0',40,44);
   label(this,p,x+120,448,map?map.name:'Карта Проклятого леса',17).setWordWrapWidth(w-144);
   label(this,p,x+120,480,map?map.description:'Вставьте карту из рюкзака. Карты доступны у картографа.',14,'#c6b698').setWordWrapWidth(w-144);
   button(this,p,x+Math.round((w-300)/2),577,300,'Открыть проход',()=>this.launchSelectedMap()).setAlpha(map?1:.5);
  },
  drawCanvasHelp(){const x=this.panelX+105,y=this.modalTop;button(this,this.canvasPanel,x,y+85,330,'Продолжить',()=>closePanel());button(this,this.canvasPanel,x,y+130,330,'Полный экран · F10',()=>toggleFullscreen(this));label(this,this.canvasPanel,x+165,y+179,'Alt — показать добычу · Z — закрепить',14).setOrigin(.5);},
  returnToHub(){state.panel=null;state.search=null;state.mode='hub';this.startHub();},
  drawCanvasResult(){const x=this.panelX+80,y=this.modalTop;label(this,this.canvasPanel,x,y+82,this.resultSuccess?'ЭВАКУАЦИЯ УСПЕШНА':'ВЫЛАЗКА ПОТЕРЯНА',21,this.resultSuccess?'#ded294':'#c35757');label(this,this.canvasPanel,x,y+135,this.resultSuccess?'Добыча сохранена.':'Снаряжение и рюкзак потеряны.\nТайник в убежище уцелел.',15);button(this,this.canvasPanel,x,y+226,340,'Вернуться в убежище',()=>this.returnToHub());},
  openCanvasLevel(options,apply){
   this.levelChoices={options,apply};this.openCanvasPanel('level');const p=this.canvasPanel;p.removeAll(true);
   p.add(this.add.zone(0,0,this.uiWidth,this.uiHeight).setOrigin(0).setInteractive());const x=Math.round((this.uiWidth-460)/2),y=Math.round((this.uiHeight-350)/2);frame(this,p,x,y,460,350);label(this,p,x+230,y+24,'СИЛА ПРОБУЖДАЕТСЯ',20).setOrigin(.5);
   options.forEach((o,i)=>{button(this,p,x+30,y+70+i*84,400,o.name,()=>{apply(o);state.panel=null;this.closeCanvasPanel();this.renderOverlay(true);const resume=this.resumePanel;this.resumePanel=null;if(resume)openPanel(resume.panel,resume.search);});label(this,p,x+40,y+103+i*84,o.text,14).setWordWrapWidth(380);});this.markUI(p);
  },
  resize(){this.uiScale=uiScaleFor(this.scale.gameSize.width,this.scale.gameSize.height);this.uiWidth=Math.floor(this.scale.gameSize.width/this.uiScale);this.uiHeight=Math.floor(this.scale.gameSize.height/this.uiScale);this.cameras.main.setZoom(worldScaleFor(this.scale.gameSize.height)).setRoundPixels(true);this.uiCamera?.setSize(this.scale.gameSize.width,this.scale.gameSize.height).setOrigin(0).setZoom(this.uiScale);this.vignette?.setDisplaySize(this.scale.gameSize.width,this.scale.gameSize.height);if(this.ui?.active)this.renderOverlay(true);if(state.panel==='level'&&this.levelChoices)this.openCanvasLevel(this.levelChoices.options,this.levelChoices.apply);else if(state.panel)this.openCanvasPanel(state.panel,state.search);},
  drawMap(hub){const random=rng(hub?72:this.seed);this.solidProps=[];const tex=this.textures.get(hub?'original-fall-0':'original-floor-0');if(!tex.has('tile-0'))for(let y=0;y<tex.source[0].height/32;y++)for(let x=0;x<14;x++)tex.add(`tile-${y*14+x}`,0,x*32,y*32,32,32);
   const wall=this.textures.get('original-wall-0');if(!wall.has('cap')){wall.add('cap',0,0,0,64,24);wall.add('face',0,0,24,48,72);}
   for(let y=0;y<this.map.h;y++)for(let x=0;x<this.map.w;x++){if(this.map.tiles[y][x]){this.add.image(x*32,y*32,tex.key,`tile-${(y%4)*14+2+x%12}`).setOrigin(0).setDepth(-50);}else if(this.map.tiles[y+1]?.[x]){this.add.image(x*32,y*32-30,'original-wall-0','face').setOrigin(0).setDisplaySize(32,62).setDepth(-10);this.add.image(x*32,y*32-42,'original-wall-0','cap').setOrigin(0).setDisplaySize(32,16).setDepth(-9);}else if(this.map.tiles[y]?.[x-1]||this.map.tiles[y]?.[x+1])this.add.image(x*32,y*32,'original-wall-0','cap').setOrigin(0).setDisplaySize(32,32).setDepth(-9);}
   if(hub){this.add.image(544,240,'hs-town-hall-0').setOrigin(.5,1).setDepth(240);for(const [x,y] of [[250,260],[830,260],[260,665],[835,665]])this.torch(x,y);for(const [x,y,key] of [[140,430,'hs-dead-tree-0'],[940,440,'hs-dead-tree2-0'],[180,660,'hs-dead-tree-0'],[910,730,'hs-dead-tree2-0'],[360,480,'hs-street-lamp-0'],[760,490,'hs-street-lamp-right-0'],[270,535,'hs-bush-0'],[800,610,'hs-rock-0']])this.placeWorldProp(x,y,key,1);for(let n=0;n<45;n++){const x=100+random()*890,y=250+random()*480;if(Math.abs(x-540)<150)continue;this.placeWorldProp(x,y,n%3?'hs-bush-0':'original-rubble-0',.4+random()*.3);}}
   else for(const [index,r] of this.map.rooms.entries()){this.torch((r.x+1)*32,(r.y+1)*32);this.torch((r.x+r.w-1)*32,(r.y+r.h-2)*32);const keys=['rack','books','cage','bench','table'];const key=keys[index%keys.length];this.placeWorldProp((r.x+r.w-3)*32,(r.y+3)*32,`original-${key}-0`,key==='table'?1:.5);for(let n=0;n<8;n++){const px=(r.x+1+random()*(r.w-2))*32,py=(r.y+1+random()*(r.h-2))*32;if(Math.abs(px-(r.cx*32+16))<70&&Math.abs(py-(r.cy*32+16))<70)continue;this.placeWorldProp(px,py,n%3===0?'original-rubble-0':n%3===1?'hs-chains-0':'original-body-0',n%3===0?.5:1);}}
  },
  startRaid(){baseRaid.call(this);const random=this.random;for(const [index,r]of this.map.rooms.entries()){for(let n=0;n<3;n++){const x=(r.x+2+n*2)*32+16,y=(r.y+r.h-2)*32;const kind=['barrel','chest','books','rack','body'][((index+n)%5)];const o=this.addObject('container',x,y,`original-${kind}-0`,{barrel:'Бочка с припасами',chest:'Деревянный сундук',books:'Книжный шкаф',rack:'Стойка с оружием',body:'Останки искателя'}[kind]);o.grid=grid(kind==='rack'?5:4,4);o.revealed=0;o.progress=0;for(let j=0;j<2+Math.floor(random()*3);j++)put(o.grid,rollLoot(random));}for(let n=0;n<3;n++){const it=rollLoot(random),x=(r.x+3+random()*(r.w-6))*32,y=(r.y+3+random()*(r.h-6))*32;const o=this.addObject('pickup',x,y,this.groundItemTexture(it),it.name);o.item=it;o.sprite.setScale(.65);}}
   this.updateFog();},
  interact(o){if(state.panel)return;if(Math.hypot(o.x-this.hero.x,o.y-this.hero.y)>76){this.pendingInteraction=o;this.interactionPath=flowField(this.map,Math.floor(o.x/32),Math.floor(o.y/32));return;}if(state.mode==='raid'&&!this.visibleTiles.has(Math.floor(o.y/32)*this.map.w+Math.floor(o.x/32)))return;if(o.type==='pickup'){if(!put(state.profile.bag,o.item))return toast('Рюкзак заполнен');o.sprite?.destroy();o.label?.destroy();this.objects=this.objects.filter(v=>v!==o);save();toast(`Подобрано: ${o.item.name}`);return;}baseInteract.call(this,o);},
  createFog(){
   this.explored=new Set();this.visibleTiles=new Set();this.fogStamp=-1;
   if(this.textures.exists('exploration-fog'))this.textures.remove('exploration-fog');
   this.fogTexture=this.textures.createCanvas('exploration-fog',this.map.w*2,this.map.h*2);
   this.fogTexture.setFilter(Phaser.Textures.FilterMode.LINEAR);
   this.fog=this.add.image(0,0,'exploration-fog').setOrigin(0).setDisplaySize(this.map.w*32,this.map.h*32).setDepth(6900);
   this.fogBuffer=document.createElement('canvas');this.fogBuffer.width=this.map.w*2;this.fogBuffer.height=this.map.h*2;this.updateFog();
  },
  updateFog(){if(!this.fog||state.mode!=='raid')return;const tx=Math.floor(this.hero.x/32),ty=Math.floor(this.hero.y/32),stamp=ty*this.map.w+tx;if(stamp===this.fogStamp)return;this.fogStamp=stamp;this.visibleTiles=new Set();
   for(let y=ty-18;y<=ty+18;y++)for(let x=tx-18;x<=tx+18;x++)if(x>=0&&y>=0&&x<this.map.w&&y<this.map.h&&Math.hypot(x-tx,y-ty)<18&&lineOfSight(this.map,tx,ty,x,y)){this.visibleTiles.add(y*this.map.w+x);this.explored.add(y*this.map.w+x);}
   const ctx=this.fogBuffer.getContext('2d');ctx.clearRect(0,0,this.fogBuffer.width,this.fogBuffer.height);ctx.fillStyle='#070608';ctx.fillRect(0,0,this.fogBuffer.width,this.fogBuffer.height);
   const fringe=new Set();for(const key of this.visibleTiles){const x=key%this.map.w,y=Math.floor(key/this.map.w);for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++)if(x+dx>=0&&y+dy>=0&&x+dx<this.map.w&&y+dy<this.map.h)fringe.add((y+dy)*this.map.w+x+dx);}
   for(const key of this.explored){const x=key%this.map.w,y=Math.floor(key/this.map.w);ctx.clearRect(x*2,y*2,2,2);ctx.fillStyle='rgba(7,6,8,.68)';ctx.fillRect(x*2,y*2,2,2);}
   for(const key of fringe)ctx.clearRect(key%this.map.w*2,Math.floor(key/this.map.w)*2,2,2);
   const output=this.fogTexture.context;output.clearRect(0,0,this.fogBuffer.width,this.fogBuffer.height);output.filter='blur(2px)';output.drawImage(this.fogBuffer,0,0);output.filter='none';this.fogTexture.refresh();
  },
  update(time,delta){if(this.keys&&['W','A','S','D','UP','DOWN','LEFT','RIGHT'].some(k=>this.keys[k].isDown))this.pendingInteraction=null;baseUpdate.call(this,time,delta);if(!this.hero)return;
if(this.pendingInteraction&&!state.panel&&state.mode!=='result'){const o=this.pendingInteraction;if(Math.hypot(o.x-this.hero.x,o.y-this.hero.y)<(o.type==='walk'?5:70)){this.pendingInteraction=null;if(o.type!=='walk')this.interact(o);}else {const tx=Math.floor(this.hero.x/32),ty=Math.floor(this.hero.y/32);let best=this.interactionPath?.[ty]?.[tx]??Infinity,target={x:o.x,y:o.y};for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const n=this.interactionPath?.[ty+dy]?.[tx+dx]??Infinity;if(n<best){best=n;target={x:(tx+dx)*32+16,y:(ty+dy)*32+16};}}const a=Math.atan2(target.y-this.hero.y,target.x-this.hero.x);this.moveBody(this.hero,Math.cos(a)*165*Math.min(delta/1000,.05),Math.sin(a)*165*Math.min(delta/1000,.05));this.setHeroDirection(Math.cos(a),Math.sin(a));}}
this.animateHero(time/1000,!!this.pendingInteraction||!!(this.keys.W.isDown||this.keys.A.isDown||this.keys.S.isDown||this.keys.D.isDown||this.keys.UP.isDown||this.keys.DOWN.isDown||this.keys.LEFT.isDown||this.keys.RIGHT.isDown));for(const o of this.objects){const near=Math.hypot(o.x-this.hero.x,o.y-this.hero.y)<100,visible=state.mode!=='raid'||this.visibleTiles.has(Math.floor(o.y/32)*this.map.w+Math.floor(o.x/32));o.sprite?.setVisible(visible);o.label?.setVisible(visible&&near);}for(const e of this.enemies)e.sprite.setVisible(this.visibleTiles.has(Math.floor(e.sprite.y/32)*this.map.w+Math.floor(e.sprite.x/32)));if(state.mode==='hub')this.renderOverlay();},
 });
}
